In [9]:
def row_info(row):
        
    ground_truth_reasoning = row['ground_truth_reasoning']
    model_response = row['model_response']

    print("LLM:", row['llm'])
    print("length of ground_truth_reasoning:", len(ground_truth_reasoning))
    print("length of model_response:", len(model_response))
    print('* ground_truth_reasoning:\n', ground_truth_reasoning)
    print('* model_response:\n', model_response)

    print()
    itmes = row['model_response'].values[0].split('A:')

    if not len(itmes) > 1:
        print("No structred output !!")
    len(itmes)

def show_model_output(df, id, llm_name):
    out = df[(df['query_uid'] == id) & (df["llm"] == llm_name)].iloc[0].model_response
    print(out)
    return out
def show_query(df, id):
    out = df[df['query_uid'] == id].iloc[0].query
    print(out)
    return out

import re
def check_structure(text):
    if len(text.split('A:')) > 1:
        return True
    # answer_patterns = [
    #     r"A:\s*(.*)$",
    #     r"Answer:\s*(.*)$"
    # ]

    # for pattern in answer_patterns:
    #     match = re.search(pattern, text, flags=re.IGNORECASE)
    #     if match:
    #         return True
    return False
    
def structure_info(df):
	print("Wrong Structure output:", len(df[(df['structure_response']==False )]))# & (df['effect']==0)
	print("Structured output:", len(df[(df['structure_response']==True )]))# & (df['effect']==0)
	print("Structured output with correct answer:", len(df[(df['structure_response']==True & (df['effect']==1))]))# 
	print("Structured output with wrong answer:", len(df[(df['structure_response']==True & (df['effect']==0))]))# 

def correct_cost(df):
	mask = df['cost'] > 1

	df.loc[mask, 'cost'] = (
		df[mask]
		.groupby('task_id')['cost']
		.transform(lambda x: (x - x.min()) / (x.max() - x.min() + 1e-8))
	)

	return df

In [ ]:
import pandas as pd
#hendrycks-MATH
DATASET = "GSM8K"
final_data = f'data/{DATASET}/final_data.csv'
final_df = pd.read_csv(final_data)
final_df

In [18]:
import pandas as pd
# hendrycks-MATH
DATASET = "hendrycks-MATH"
# DATASET = "GSM8K"
# DATASET ="MIZAN_PersianNLG"

ROUTER_PATH = f'data/{DATASET}/router_data.csv'
df = pd.read_csv(ROUTER_PATH)



print(len(df['query_uid'].unique()))
unified_data = pd.read_csv(f'data/{DATASET}/unified_data.csv')
# unified_data.shape
df

104

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,OMS,RM_metric,RQS_metric
0,hendrycks-MATH::00958680c17d2177::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 5.15792705e-02 1.84012745e-02 -4.15192135e-...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is \( y...,exact_match,GPT-4.1,0.000000,6.798902e-01,00958680c17d2177,0.000000,0,0.930107
1,hendrycks-MATH::00958680c17d2177::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 5.15792705e-02 1.84012745e-02 -4.15192135e-...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is $y =...,exact_match,Gemini 2.5 Pro,0.000000,8.263426e-01,00958680c17d2177,0.000000,0,0.883817
2,hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 5.15792705e-02 1.84012745e-02 -4.15192135e-...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,LLlama-3.1 (8B),0.000000,1.273537e-11,00958680c17d2177,0.000000,0,0.892590
3,hendrycks-MATH::00958680c17d2177::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 5.15792705e-02 1.84012745e-02 -4.15192135e-...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.000000,2.420482e-09,00958680c17d2177,0.000000,0,0.844519
4,hendrycks-MATH::00958680c17d2177::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 5.15792705e-02 1.84012745e-02 -4.15192135e-...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe equation of the directrix of a parabo...,exact_match,Mixtral-8x7B Instruct v0.1,0.000000,1.457384e-09,00958680c17d2177,0.000000,0,0.863945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,hendrycks-MATH::f9320a8c7847649a::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 2.60981414e-02 -4.07927483e-02 -7.29585886e-...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the positive value of the expressi...,exact_match,LLlama-3.1 (8B),0.000000,2.449110e-11,f9320a8c7847649a,0.000000,0,0.864017
724,hendrycks-MATH::f9320a8c7847649a::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 2.60981414e-02 -4.07927483e-02 -7.29585886e-...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the value of the expression $\sqrt...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.912326,2.477955e-09,f9320a8c7847649a,0.912326,1,0.874751
725,hendrycks-MATH::f9320a8c7847649a::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 2.60981414e-02 -4.07927483e-02 -7.29585886e-...,11,"Plugging in, the desired expression is just $\...",R:\nGiven the expression $\sqrt{x^3 - 2^y}$ a...,exact_match,Mixtral-8x7B Instruct v0.1,0.928557,1.496569e-09,f9320a8c7847649a,0.928557,1,0.897939
726,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 2.60981414e-02 -4.07927483e-02 -7.29585886e-...,11,"Plugging in, the desired expression is just $\...",R:\nTo solve the expression \(\sqrt{x^3 - 2^y}...,exact_match,Qwen2.5 72B Instruct Turbo,0.890285,3.599538e-09,f9320a8c7847649a,0.890285,1,0.843264
727,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[ 2.60981414e-02 -4.07927483e-02 -7.29585886e-...,11,"Plugging in, the desired expression is just $\...","R:\nGiven the expression $\sqrt{x^3 - 2^y}$, w...",exact_match,Qwen2.5 7B Instruct Turbo,0.754991,4.450849e-10,f9320a8c7847649a,0.754991,1,0.649987

## Update the task description embeddings

In [26]:
task_description= "The GSM8K dataset is tailored for mathematical problem-solving tasks. It consists of natural language math problems that require the model to comprehend the problem statement, apply the correct mathematical operations, and provide the solution. The primary challenge lies in both parsing complex language and performing accurate calculations."
df['task_description'] = task_description

df['task_description']

0       The GSM8K dataset is tailored for mathematical...
1       The GSM8K dataset is tailored for mathematical...
2       The GSM8K dataset is tailored for mathematical...
3       The GSM8K dataset is tailored for mathematical...
4       The GSM8K dataset is tailored for mathematical...
                              ...
5703    The GSM8K dataset is tailored for mathematical...
5704    The GSM8K dataset is tailored for mathematical...
5705    The GSM8K dataset is tailored for mathematical...
5706    The GSM8K dataset is tailored for mathematical...
5707    The GSM8K dataset is tailored for mathematical...
Name: task_description, Length: 5708, dtype: object

In [27]:
from data_processing.utils import get_embedding, loadjson

task_desc_embedding = get_embedding([task_description])
df['task_description_embedding'] = str(task_desc_embedding)

In [16]:
task_description= "The hendrycks-MATH-benchmark (based on the MATH dataset) is designed for advanced mathematical reasoning and problem-solving tasks. It consists of high school competition-level mathematics problems (drawn from sources like AMC 10/12, AIME) across subjects such as Prealgebra, Algebra, Number Theory, Counting & Probability, Geometry, Intermediate Algebra, and Precalculus, with difficulty levels from 1 (easiest) to 5 (hardest). The model must comprehend complex problem statements, apply appropriate mathematical concepts and techniques, perform step-by-step derivations or proofs when needed, and arrive at the correct final numerical or symbolic answer (often presented in boxed format). The primary challenge lies in deep conceptual understanding, multi-step logical reasoning, and accurate computation without relying on simple pattern matching."
df['task_description'] = task_description

df['task_description']

0      The hendrycks-MATH-benchmark (based on the MAT...
1      The hendrycks-MATH-benchmark (based on the MAT...
2      The hendrycks-MATH-benchmark (based on the MAT...
3      The hendrycks-MATH-benchmark (based on the MAT...
4      The hendrycks-MATH-benchmark (based on the MAT...
                             ...
411    The hendrycks-MATH-benchmark (based on the MAT...
412    The hendrycks-MATH-benchmark (based on the MAT...
413    The hendrycks-MATH-benchmark (based on the MAT...
414    The hendrycks-MATH-benchmark (based on the MAT...
415    The hendrycks-MATH-benchmark (based on the MAT...
Name: task_description, Length: 416, dtype: object

In [21]:
from data_processing.utils import get_embedding, loadjson

task_desc_embedding = get_embedding([task_description])
df['task_description_embedding'] = str(task_desc_embedding)

In [28]:
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,EM_metric,RQS_metric
0,GSM8K::001d09626d614475::LLlama-3.1 (8B),GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, find the number of pies eaten with f...",exact_match,LLlama-3.1 (8B),0.966941,0.005552,001d09626d614475,0.974570,0.963671
1,GSM8K::001d09626d614475::Meta Llama 3.1 70B In...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, find the number of pies eaten with f...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0.959004,0.126645,001d09626d614475,0.968465,0.954949
2,GSM8K::001d09626d614475::Mixtral-8x7B Instruct...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...",R: First find the number of pies eaten with f...,exact_match,Mixtral-8x7B Instruct v0.1,0.956071,0.080831,001d09626d614475,0.966208,0.951726
3,GSM8K::001d09626d614475::Qwen2.5 7B Instruct T...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, calculate the number of pies eaten w...",exact_match,Qwen2.5 7B Instruct Turbo,0.955524,0.023899,001d09626d614475,0.965788,0.951125
4,GSM8K::00d32ecffad5ac5a::LLlama-3.1 (8B),GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.35455709e-02 7.90544972e-02 4.33345102e-...,1000,The cost of the hearing aids is $2500 * 2 = $<...,"R: First, find the total cost of the hearing a...",exact_match,LLlama-3.1 (8B),0.934770,0.010863,00d32ecffad5ac5a,0.949823,0.928319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5703,GSM8K::7d62822c57680bfe::Qwen2.5 7B Instruct T...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 3.53983231e-02 5.52317686e-02 -7.64585063e-...,162,Let x represent the score of the third bowler\...,R: Let the third bowler's score be \(x\). The ...,exact_match,Qwen2.5 7B Instruct Turbo,0.833235,0.032147,7d62822c57680bfe,0.640950,0.915643
5704,GSM8K::2ed52ab4539e0fd1::Mixtral-8x7B Instruct...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 4.40676473e-02 4.39128876e-02 3.90084684e-...,2,First find the total number of strands the two...,"R: First, find the total number of duct tape ...",exact_match,Mixtral-8x7B Instruct v0.1,0.897356,0.114628,2ed52ab4539e0fd1,0.921043,0.887205
5705,GSM8K::2ed52ab4539e0fd1::Meta Llama 3.1 70B In...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 4.40676473e-02 4.39128876e-02 3.90084684e-...,2,First find the total number of strands the two...,"R: First, find the total number of strands the...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0.904478,0.145528,2ed52ab4539e0fd1,0.926522,0.895031
5706,GSM8K::2ed52ab4539e0fd1::LLlama-3.1 (8B),GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 4.40676473e-02 4.39128876e-02 3.90084684e-...,2,First find the total number of strands the two...,"R: First, find the combined rate at which Hann...",exact_match,LLlama-3.1 (8B),0.858216,0.009294,2ed52ab4539e0fd1,0.890935,0.844193
5707,GSM8K::2ed52ab4539e0fd1::Qwen2.5 7B Instruct T...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 4.40676473e-02 4.39128876e-02 3.90084684e-...,2,First find the total number of strands the two...,"R: First, determine the total rate at which Ha...",exact_match,Qwen2.5 7B Instruct Turbo,0.881856,0.031141,2ed52ab4539e0fd1,0.909120,0.870171

In [29]:
df.to_csv(ROUTER_PATH, index=False)

## Update the Cost

In [5]:
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

def compute_cost(llm_description: dict, llm_name: str, input_text: str, output_text: int) -> float:
    input_size = len(tokenizer(input_text)['input_ids'])
    output_size = len(tokenizer(output_text)['input_ids'])


    input_price = llm_description[llm_name]["input_price"]
    output_price = llm_description[llm_name]["output_price"]

    cost = input_size * input_price + output_size * output_price
    return cost
from data_processing.utils import get_embedding, loadjson
llm_description = loadjson(f"data/{DATASET}/LLM_Descriptions.json")


# Apply row-wise
df['cost_new'] = df.apply(
    lambda row: compute_cost(
        llm_description=llm_description,
        llm_name=row['llm'],
        input_text=row['query'],
        output_text=row['model_response']
    ),
    axis=1
)

WARNING:tensorflow:From c:\Users\CMG\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Token indices sequence length is longer than the specified maximum sequence length for this model (2198 > 1024). Running this sequence through the model will result in indexing errors

In [6]:
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,OMS,RM_metric,RQS_metric,cost_new
0,hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,LLlama-3.1 (8B),0.000000,1.273537e-11,00958680c17d2177,0.000000,0,0.892590,79.38
1,hendrycks-MATH::00958680c17d2177::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.000000,2.420482e-09,00958680c17d2177,0.000000,0,0.844519,342.32
2,hendrycks-MATH::00958680c17d2177::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe equation of the directrix of a parabo...,exact_match,Mixtral-8x7B Instruct v0.1,0.000000,1.457384e-09,00958680c17d2177,0.000000,0,0.863945,300.00
3,hendrycks-MATH::00958680c17d2177::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is \( y...,exact_match,Qwen2.5 7B Instruct Turbo,0.000000,4.254920e-10,00958680c17d2177,0.000000,0,0.710457,123.90
4,hendrycks-MATH::02c2417dd6dbfc9b::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.87501857e-02 1.19769767e-01 6.25698343e...,x^4-5x^3+2x^2+x-19,We use synthetic division.\n\[\n\begin{array}{...,R:\nTo find the quotient when $x^5-23x^3+11x^2...,exact_match,LLlama-3.1 (8B),0.000000,1.814818e-02,02c2417dd6dbfc9b,0.000000,0,0.894931,140.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,hendrycks-MATH::f56d7bcf617da5d7::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-1.01652192e-02 1.68272167e-01 -2.73055155e...,1.36,"Since Alice wants to buy $3$ pounds of veal, w...","R:\n1. First, we need to convert the weight Al...",exact_match,Qwen2.5 7B Instruct Turbo,0.937935,5.005980e-10,f56d7bcf617da5d7,0.937935,1,0.911336,109.80
412,hendrycks-MATH::f9320a8c7847649a::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the positive value of the expressi...,exact_match,LLlama-3.1 (8B),0.000000,2.449110e-11,f9320a8c7847649a,0.000000,0,0.864017,74.88
413,hendrycks-MATH::f9320a8c7847649a::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the value of the expression $\sqrt...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.912326,2.477955e-09,f9320a8c7847649a,0.912326,1,0.874751,324.72
414,hendrycks-MATH::f9320a8c7847649a::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nGiven the expression $\sqrt{x^3 - 2^y}$ a...,exact_match,Mixtral-8x7B Instruct v0.1,0.928557,1.496569e-09,f9320a8c7847649a,0.928557,1,0.897939,160.80
415,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...","R:\nGiven the expression $\sqrt{x^3 - 2^y}$, w...",exact_match,Qwen2.5 7B Instruct Turbo,0.754991,4.450849e-10,f9320a8c7847649a,0.754991,1,0.649987,87.90

In [7]:
df['cost'] = df['cost_new']
df = df.drop('cost_new', axis=1)

In [10]:
df = correct_cost(df)
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,OMS,RM_metric,RQS_metric
0,hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,LLlama-3.1 (8B),0.000000,0.015879,00958680c17d2177,0.000000,0,0.892590
1,hendrycks-MATH::00958680c17d2177::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.000000,0.114165,00958680c17d2177,0.000000,0,0.844519
2,hendrycks-MATH::00958680c17d2177::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe equation of the directrix of a parabo...,exact_match,Mixtral-8x7B Instruct v0.1,0.000000,0.098346,00958680c17d2177,0.000000,0,0.863945
3,hendrycks-MATH::00958680c17d2177::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is \( y...,exact_match,Qwen2.5 7B Instruct Turbo,0.000000,0.032520,00958680c17d2177,0.000000,0,0.710457
4,hendrycks-MATH::02c2417dd6dbfc9b::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.87501857e-02 1.19769767e-01 6.25698343e...,x^4-5x^3+2x^2+x-19,We use synthetic division.\n\[\n\begin{array}{...,R:\nTo find the quotient when $x^5-23x^3+11x^2...,exact_match,LLlama-3.1 (8B),0.000000,0.038755,02c2417dd6dbfc9b,0.000000,0,0.894931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,hendrycks-MATH::f56d7bcf617da5d7::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-1.01652192e-02 1.68272167e-01 -2.73055155e...,1.36,"Since Alice wants to buy $3$ pounds of veal, w...","R:\n1. First, we need to convert the weight Al...",exact_match,Qwen2.5 7B Instruct Turbo,0.937935,0.027250,f56d7bcf617da5d7,0.937935,1,0.911336
412,hendrycks-MATH::f9320a8c7847649a::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the positive value of the expressi...,exact_match,LLlama-3.1 (8B),0.000000,0.014197,f9320a8c7847649a,0.000000,0,0.864017
413,hendrycks-MATH::f9320a8c7847649a::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the value of the expression $\sqrt...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.912326,0.107586,f9320a8c7847649a,0.912326,1,0.874751
414,hendrycks-MATH::f9320a8c7847649a::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nGiven the expression $\sqrt{x^3 - 2^y}$ a...,exact_match,Mixtral-8x7B Instruct v0.1,0.928557,0.046313,f9320a8c7847649a,0.928557,1,0.897939
415,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...","R:\nGiven the expression $\sqrt{x^3 - 2^y}$, w...",exact_match,Qwen2.5 7B Instruct Turbo,0.754991,0.019064,f9320a8c7847649a,0.754991,1,0.649987

In [ ]:
df.to_csv(ROUTER_PATH, index=False)

## Remove Extra LLMs

In [ ]:
df_filtered = df[~df['llm'].isin(['GPT-4.1', 'Gemini 2.5 Pro', 'Qwen2.5 72B Instruct Turbo'])]
df_filtered[:5]

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,OMS,RM_metric,RQS_metric
2,hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,LLlama-3.1 (8B),0.0,1.273537e-11,00958680c17d2177,0.0,0,0.892590
3,hendrycks-MATH::00958680c17d2177::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.0,2.420482e-09,00958680c17d2177,0.0,0,0.844519
4,hendrycks-MATH::00958680c17d2177::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe equation of the directrix of a parabo...,exact_match,Mixtral-8x7B Instruct v0.1,0.0,1.457384e-09,00958680c17d2177,0.0,0,0.863945
6,hendrycks-MATH::00958680c17d2177::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is \( y...,exact_match,Qwen2.5 7B Instruct Turbo,0.0,4.254920e-10,00958680c17d2177,0.0,0,0.710457
9,hendrycks-MATH::02c2417dd6dbfc9b::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.87501857e-02 1.19769767e-01 6.25698343e...,x^4-5x^3+2x^2+x-19,We use synthetic division.\n\[\n\begin{array}{...,R:\nTo find the quotient when $x^5-23x^3+11x^2...,exact_match,LLlama-3.1 (8B),0.0,1.814818e-02,02c2417dd6dbfc9b,0.0,0,0.894931

In [ ]:
df_filtered.to_csv(f'data/{DATASET}/_router_data.csv', index=False)

## Concat The Router Datasets

In [15]:
from data_processing.utils import loadpkl

llm_description_embedding = loadpkl(f"data/GSM8K/llm_description_embedding.pkl")
llm_description_embedding.shape

(4, 384)

In [19]:
hendtycks_df = pd.read_csv(f"data/hendrycks-MATH/_router_data.csv")
GSM8K_df = pd.read_csv(f"data/GSM8K/router_data.csv")

newdf = pd.concat([GSM8K_df, hendtycks_df])
newdf

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,EM_metric,RQS_metric
0,GSM8K::001d09626d614475::LLlama-3.1 (8B),GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, find the number of pies eaten with f...",exact_match,LLlama-3.1 (8B),0.966941,0.005552,001d09626d614475,0.974570,0.963671
1,GSM8K::001d09626d614475::Meta Llama 3.1 70B In...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, find the number of pies eaten with f...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0.959004,0.126645,001d09626d614475,0.968465,0.954949
2,GSM8K::001d09626d614475::Mixtral-8x7B Instruct...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...",R: First find the number of pies eaten with f...,exact_match,Mixtral-8x7B Instruct v0.1,0.956071,0.080831,001d09626d614475,0.966208,0.951726
3,GSM8K::001d09626d614475::Qwen2.5 7B Instruct T...,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.38209432e-01 4.20225635e-02 8.51342734e-...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, calculate the number of pies eaten w...",exact_match,Qwen2.5 7B Instruct Turbo,0.955524,0.023899,001d09626d614475,0.965788,0.951125
4,GSM8K::00d32ecffad5ac5a::LLlama-3.1 (8B),GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763260e-02 8.01854804e-02 3.90714929e...,"Given a simple mathematical question, please d...",[ 1.35455709e-02 7.90544972e-02 4.33345102e-...,1000,The cost of the hearing aids is $2500 * 2 = $<...,"R: First, find the total cost of the hearing a...",exact_match,LLlama-3.1 (8B),0.934770,0.010863,00d32ecffad5ac5a,0.949823,0.928319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,hendrycks-MATH::f56d7bcf617da5d7::Qwen2.5 7B I...,hendrycks-MATH,The hendrycks-MATH-benchmark (based on the MAT...,[[-1.75816845e-02 4.31099162e-02 2.65894290e...,You are given a mathematics problem.\n\nSolve ...,[[-1.01652192e-02 1.68272167e-01 -2.73055155e...,1.36,"Since Alice wants to buy $3$ pounds of veal, w...","R:\n1. First, we need to convert the weight Al...",exact_match,Qwen2.5 7B Instruct Turbo,0.950601,0.027250,f56d7bcf617da5d7,1.000000,0.929430
412,hendrycks-MATH::f9320a8c7847649a::LLlama-3.1 (8B),hendrycks-MATH,The hendrycks-MATH-benchmark (based on the MAT...,[[-1.75816845e-02 4.31099162e-02 2.65894290e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the positive value of the expressi...,exact_match,LLlama-3.1 (8B),0.610902,0.014197,f9320a8c7847649a,0.000000,0.872717
413,hendrycks-MATH::f9320a8c7847649a::Meta Llama 3...,hendrycks-MATH,The hendrycks-MATH-benchmark (based on the MAT...,[[-1.75816845e-02 4.31099162e-02 2.65894290e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the value of the expression $\sqrt...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.921871,0.107586,f9320a8c7847649a,1.000000,0.888387
414,hendrycks-MATH::f9320a8c7847649a::Mixtral-8x7B...,hendrycks-MATH,The hendrycks-MATH-benchmark (based on the MAT...,[[-1.75816845e-02 4.31099162e-02 2.65894290e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nGiven the expression $\sqrt{x^3 - 2^y}$ a...,exact_match,Mixtral-8x7B Instruct v0.1,0.932890,0.046313,f9320a8c7847649a,1.000000,0.904129
415,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 7B I...,hendrycks-MATH,The hendrycks-MATH-benchmark (based on the MAT...,[[-1.75816845e-02 4.31099162e-02 2.65894290e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...","R:\nGiven the expression $\sqrt{x^3 - 2^y}$, w...",exact_match,Qwen2.5 7B Instruct Turbo,0.765737,0.019064,f9320a8c7847649a,1.000000,0.665339

In [20]:
newdf.to_csv('data/router_data.csv', index=False)

## Remove Insturction

In [3]:
from data_processing.instructions import *
from data_processing.utils import get_embedding, loadjson

# llm_description = loadjson("data/LLM_Descriptions.json")
# llm_names = list(llm_description.keys())

# all_llm_description = [
# 	llm_description[n]['feature'] for n in llm_names
# ]

In [5]:
def update_embeds(q):
	return q.replace(MATH_INSTRUCTION, '').replace('\n', '')

df['updated_query'] = df['query'].apply(update_embeds)

In [6]:
def update_embeds(q):
	return get_embedding(q)

df['updated_query_embeds'] = df['updated_query'].apply(update_embeds)

In [7]:
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,OMS,RM_metric,RQS_metric,updated_query,updated_query_embeds
0,hendrycks-MATH::00958680c17d2177::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is \( y...,exact_match,GPT-4.1,0.000000,6.798902e-01,00958680c17d2177,0.000000,0,0.930107,Find the equation of the directrix of the para...,"[0.05157927, 0.018401274, -0.041519213, 0.0014..."
1,hendrycks-MATH::00958680c17d2177::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is $y =...,exact_match,Gemini 2.5 Pro,0.000000,8.263426e-01,00958680c17d2177,0.000000,0,0.883817,Find the equation of the directrix of the para...,"[0.05157927, 0.018401274, -0.041519213, 0.0014..."
2,hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,LLlama-3.1 (8B),0.000000,1.273537e-11,00958680c17d2177,0.000000,0,0.892590,Find the equation of the directrix of the para...,"[0.05157927, 0.018401274, -0.041519213, 0.0014..."
3,hendrycks-MATH::00958680c17d2177::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.000000,2.420482e-09,00958680c17d2177,0.000000,0,0.844519,Find the equation of the directrix of the para...,"[0.05157927, 0.018401274, -0.041519213, 0.0014..."
4,hendrycks-MATH::00958680c17d2177::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe equation of the directrix of a parabo...,exact_match,Mixtral-8x7B Instruct v0.1,0.000000,1.457384e-09,00958680c17d2177,0.000000,0,0.863945,Find the equation of the directrix of the para...,"[0.05157927, 0.018401274, -0.041519213, 0.0014..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,hendrycks-MATH::f9320a8c7847649a::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the positive value of the expressi...,exact_match,LLlama-3.1 (8B),0.000000,2.449110e-11,f9320a8c7847649a,0.000000,0,0.864017,What is the positive value of the expression $...,"[0.026098141, -0.04079275, -0.07295859, 0.0252..."
724,hendrycks-MATH::f9320a8c7847649a::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the value of the expression $\sqrt...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0.912326,2.477955e-09,f9320a8c7847649a,0.912326,1,0.874751,What is the positive value of the expression $...,"[0.026098141, -0.04079275, -0.07295859, 0.0252..."
725,hendrycks-MATH::f9320a8c7847649a::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nGiven the expression $\sqrt{x^3 - 2^y}$ a...,exact_match,Mixtral-8x7B Instruct v0.1,0.928557,1.496569e-09,f9320a8c7847649a,0.928557,1,0.897939,What is the positive value of the expression $...,"[0.026098141, -0.04079275, -0.07295859, 0.0252..."
726,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo solve the expression \(\sqrt{x^3 - 2^y}...,exact_match,Qwen2.5 72B Instruct Turbo,0.890285,3.599538e-09,f9320a8c7847649a,0.890285,1,0.843264,What is the positive value of the expression $...,"[0.026098141, -0.04079275, -0.07295859, 0.0252..."
727,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...","R:\nGiven the expression $\sqrt{x^3 - 2^y}$, w...",exact_match,Qwen2.5 7B Instruct Turbo,0.754991,4.450849e-10,f9320a8c7847649a,0.754991,1,0.649987,What is the positive value of the expression $...,"[0.026098141, -0.04079275, -0.07295859, 0.0252..."

In [8]:
df['query_embedding'] = df['updated_query_embeds']

In [9]:
df = df.drop(['updated_query', 'updated_query_embeds'], axis=1)

In [10]:
df.to_csv(ROUTER_PATH, index=False)

In [ ]:
# mask = df['cost'] > 1

# df.loc[mask, 'cost'] = (
#     df[mask]
#     .groupby('task_id')['cost']
#     .transform(lambda x: (x - x.min()) / (x.max() - x.min() + 1e-8))
# )

# df['cost']

0       0.171515
1       0.838517
2       0.571716
3       0.285858
4       0.174696
          ...
5703    0.153895
5704    0.499198
5705    0.825072
5706    0.010388
5707    0.150048
Name: cost, Length: 5708, dtype: float64

In [56]:
df[df['effect']>0].shape

(4573, 16)

In [32]:
hendtycks_df = hendtycks_df.drop(['RM_metric', 'RQS_metric'], axis=1)

def rmmetric(rm_score):
	if rm_score > 0:
		return 1
	else:
		return 0

hendtycks_df['effect_'] =  hendtycks_df['effect'].apply(rmmetric)

In [33]:
hendtycks_df[hendtycks_df['effect']>0].shape

(222, 16)

In [34]:
hendtycks_df['effect'] = hendtycks_df['effect_']
hendtycks_df = hendtycks_df.drop('effect_', axis=1)
hendtycks_df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,OMS
0,hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,LLlama-3.1 (8B),0,1.273537e-11,00958680c17d2177,0.000000
1,hendrycks-MATH::00958680c17d2177::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nTo find the equation of the directrix of t...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0,2.420482e-09,00958680c17d2177,0.000000
2,hendrycks-MATH::00958680c17d2177::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe equation of the directrix of a parabo...,exact_match,Mixtral-8x7B Instruct v0.1,0,1.457384e-09,00958680c17d2177,0.000000
3,hendrycks-MATH::00958680c17d2177::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 3.95489894e-02 9.29614007e-02 -3.11193578e...,y = \frac{63}{32},Recall that a parabola is defined as the set o...,R:\nThe given equation of the parabola is \( y...,exact_match,Qwen2.5 7B Instruct Turbo,0,4.254920e-10,00958680c17d2177,0.000000
4,hendrycks-MATH::02c2417dd6dbfc9b::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.87501857e-02 1.19769767e-01 6.25698343e...,x^4-5x^3+2x^2+x-19,We use synthetic division.\n\[\n\begin{array}{...,R:\nTo find the quotient when $x^5-23x^3+11x^2...,exact_match,LLlama-3.1 (8B),0,1.814818e-02,02c2417dd6dbfc9b,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,hendrycks-MATH::f56d7bcf617da5d7::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-1.01652192e-02 1.68272167e-01 -2.73055155e...,1.36,"Since Alice wants to buy $3$ pounds of veal, w...","R:\n1. First, we need to convert the weight Al...",exact_match,Qwen2.5 7B Instruct Turbo,1,5.005980e-10,f56d7bcf617da5d7,0.937935
412,hendrycks-MATH::f9320a8c7847649a::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the positive value of the expressi...,exact_match,LLlama-3.1 (8B),0,2.449110e-11,f9320a8c7847649a,0.000000
413,hendrycks-MATH::f9320a8c7847649a::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nTo find the value of the expression $\sqrt...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,2.477955e-09,f9320a8c7847649a,0.912326
414,hendrycks-MATH::f9320a8c7847649a::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...",R:\nGiven the expression $\sqrt{x^3 - 2^y}$ a...,exact_match,Mixtral-8x7B Instruct v0.1,1,1.496569e-09,f9320a8c7847649a,0.928557
415,hendrycks-MATH::f9320a8c7847649a::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 9.64169763e-03 6.29825890e-02 -2.81779841e...,11,"Plugging in, the desired expression is just $\...","R:\nGiven the expression $\sqrt{x^3 - 2^y}$, w...",exact_match,Qwen2.5 7B Instruct Turbo,1,4.450849e-10,f9320a8c7847649a,0.754991

In [36]:
hendtycks_df.to_csv("data/hendrycks-MATH/_router_data.csv", index=False)

In [60]:
models_per_query = df.groupby('query_uid')['llm'].nunique()
models_per_query.value_counts()

llm
4    1427
Name: count, dtype: int64

In [23]:
# Select query_uids where number of LLMs == 7
valid_queries = models_per_query[models_per_query == 4].index
# Filter original dataframe
df_7_llms = df[df['query_uid'].isin(valid_queries)]


print("Number of valid queries:", len(valid_queries))
print("Filtered dataframe shape:", df_7_llms.shape)

Number of valid queries: 1080
Filtered dataframe shape: (4320, 14)

In [24]:
df_7_llms = df_7_llms.sort_values(by=['query_uid', 'llm']).reset_index(drop=True)

In [25]:
df_7_llms

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,GSM8K::001d09626d614475::LLlama-3.1 (8B),GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 6.89666495e-02 1.07712887e-01 1.61993746e...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, find the number of pies eaten with f...",exact_match,LLlama-3.1 (8B),1,0.171515,001d09626d614475
1,GSM8K::001d09626d614475::Meta Llama 3.1 70B In...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 6.89666495e-02 1.07712887e-01 1.61993746e...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, find the number of pies eaten with f...",exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.838517,001d09626d614475
2,GSM8K::001d09626d614475::Mixtral-8x7B Instruct...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 6.89666495e-02 1.07712887e-01 1.61993746e...,640,"If there are 2000 pies of all kinds, and 68% o...",R: First find the number of pies eaten with f...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.571716,001d09626d614475
3,GSM8K::001d09626d614475::Qwen2.5 7B Instruct T...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 6.89666495e-02 1.07712887e-01 1.61993746e...,640,"If there are 2000 pies of all kinds, and 68% o...","R: First, calculate the number of pies eaten w...",exact_match,Qwen2.5 7B Instruct Turbo,1,0.285858,001d09626d614475
4,GSM8K::00d32ecffad5ac5a::LLlama-3.1 (8B),GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 2.03387346e-03 1.50905237e-01 2.87344120e...,1000,The cost of the hearing aids is $2500 * 2 = $<...,"R: First, find the total cost of the hearing a...",exact_match,LLlama-3.1 (8B),1,0.174696,00d32ecffad5ac5a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4315,GSM8K::feeacc8a813e0e03::Qwen2.5 7B Instruct T...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 3.45542207e-02 1.47203729e-01 -1.10964142e...,13,Kimberley and Houston collected 10+12 = <<10+1...,"R: First, find the total amount of firewood co...",exact_match,Qwen2.5 7B Instruct Turbo,1,0.300130,feeacc8a813e0e03
4316,GSM8K::ff899c8d23bf7a9a::LLlama-3.1 (8B),GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 1.67966019e-02 1.08585909e-01 3.73202264e...,6,There are 15 - 6 = <<15-6=9>>9 students who li...,"R: First, find the total number of students wh...",exact_match,LLlama-3.1 (8B),1,0.179589,ff899c8d23bf7a9a
4317,GSM8K::ff899c8d23bf7a9a::Meta Llama 3.1 70B In...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 1.67966019e-02 1.08585909e-01 3.73202264e...,6,There are 15 - 6 = <<15-6=9>>9 students who li...,"R: First, find the total number of students wh...",exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.877990,ff899c8d23bf7a9a
4318,GSM8K::ff899c8d23bf7a9a::Mixtral-8x7B Instruct...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 1.67966019e-02 1.08585909e-01 3.73202264e...,6,There are 15 - 6 = <<15-6=9>>9 students who li...,"R: First, we need to find out how many studen...",exact_match,Mixtral-8x7B Instruct v0.1,1,0.598630,ff899c8d23bf7a9a
4319,GSM8K::ff899c8d23bf7a9a::Qwen2.5 7B Instruct T...,GSM8K,Grade-school math word problems.,[[ 6.38151094e-02 8.33175629e-02 1.43494215e...,"Given a simple mathematical question, please d...",[[ 1.67966019e-02 1.08585909e-01 3.73202264e...,6,There are 15 - 6 = <<15-6=9>>9 students who li...,"R: First, calculate the number of students who...",exact_match,Qwen2.5 7B Instruct Turbo,1,0.299315,ff899c8d23bf7a9a

In [26]:
df_7_llms.to_csv(ROUTER_PATH, index=False)

In [3]:
print(df.shape)
164*7

(1032, 17)

1148

In [61]:

df['cost'] = df.groupby('task_id')['cost'].transform(
	lambda x: (x - x.min()) / (x.max() - x.min() + 1e-8)
)

df['cost']

0       0.000229
1       0.001121
2       0.000764
3       0.000382
4       0.000234
          ...
5703    0.294385
5704    0.582353
5705    0.854118
5706    0.174706
5707    0.291176
Name: cost, Length: 5708, dtype: float64

In [16]:
df = df.drop('OMS', axis=1)
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::0fa23b219f0b1954::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,2.307921e-08,0fa23b219f0b1954
1,hendrycks-MATH::0fa23b219f0b1954::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,2.812982e-08,0fa23b219f0b1954
2,hendrycks-MATH::0fa23b219f0b1954::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,3.573414e-09,0fa23b219f0b1954
3,hendrycks-MATH::0fa23b219f0b1954::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,1.483507e-09,0fa23b219f0b1954
4,hendrycks-MATH::0fa23b219f0b1954::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,2.458797e-09,0fa23b219f0b1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,hendrycks-MATH::cc1c154d75400080::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.05129122e-03 1.06128246e-01 -3.29928845e...,12,"First, we label the diagram as shown below:\n\...","R:\nIn a 30-60-90 triangle, the sides are in t...",exact_match,Qwen2.5 72B Instruct Turbo,1,1.951235e-01,cc1c154d75400080
1028,hendrycks-MATH::cc1c154d75400080::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.05129122e-03 1.06128246e-01 -3.29928845e...,12,"First, we label the diagram as shown below:\n\...","R:\nIn a 30-60-90 triangle, the sides are in ...",exact_match,Mixtral-8x7B Instruct v0.1,0,9.756174e-02,cc1c154d75400080
1029,hendrycks-MATH::cc1c154d75400080::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.05129122e-03 1.06128246e-01 -3.29928845e...,12,"First, we label the diagram as shown below:\n\...","R:\nIn a 30-60-90 triangle, the ratio of the s...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0,1.430906e-01,cc1c154d75400080
1030,hendrycks-MATH::cc1c154d75400080::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.05129122e-03 1.06128246e-01 -3.29928845e...,12,"First, we label the diagram as shown below:\n\...","R:\nIn a 30-60-90 triangle, the ratio of the s...",exact_match,LLlama-3.1 (8B),1,2.926852e-02,cc1c154d75400080
1031,hendrycks-MATH::cc1c154d75400080::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.05129122e-03 1.06128246e-01 -3.29928845e...,12,"First, we label the diagram as shown below:\n\...",R:\n1. The given problem involves a series of ...,exact_match,Qwen2.5 7B Instruct Turbo,1,4.878087e-02,cc1c154d75400080

In [17]:
df.to_csv(ROUTER_PATH, index=False)

In [12]:
# filtred_df = df.drop(['effect', 'model_response'], axis=1)
# filtred_df[filtred_df.duplicated]
# df['uid'].value_counts()
# df = df.drop_duplicates(subset='uid', keep='first')
# df

In [163]:
df.to_csv(ROUTER_PATH, index=False)

In [7]:
%pip install tiktoken

Requirement already satisfied: tiktoken in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (0.9.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: regex>=2022.1.18 in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (from tiktoken) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (from tiktoken) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->tiktoken) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->tiktoken) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->tiktoken) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cmg\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->tiktoken) (2025.7.14)

In [12]:
import json, os
# File I/O functions
def loadjson(filename: str) -> dict:
    """
    Load data from a JSON file.

    Args:
        filename: Path to the JSON file

    Returns:
        Dictionary containing the loaded JSON data
    """
    with open(filename, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data
data_dir = "data/hendrycks-MATH/"
llm_path = os.path.join(data_dir, "LLM_Descriptions.json")
llm_description = loadjson(llm_path)
llm_names = list(llm_description.keys())
llm_names

['GPT-4.1',
 'Gemini 2.5 Pro',
 'Qwen2.5 72B Instruct Turbo',
 'Mixtral-8x7B Instruct v0.1',
 'Meta Llama 3.1 70B Instruct Turbo',
 'LLlama-3.1 (8B)',
 'Qwen2.5 7B Instruct Turbo']

In [14]:
llm_description['GPT-4.1']['input_price']

2.0

In [129]:
import tiktoken
import pandas as pd

# Choose the model tokenizer
encoding = tiktoken.encoding_for_model("gpt-4o-mini")  
# fallback: tiktoken.get_encoding("cl100k_base")

def count_tokens(text: str) -> int:
    if not isinstance(text, str):
        return 0
    return len(encoding.encode(text))

def calculate_price(df, llm_description):
	cost = []

	# for llm in llm_names:
		# print(f"Input cost for {llm}: { llm_description[llm]['input_price']*(unified_data["query_token_len"].sum()/1000000):.3f}")
	for row in df.groupby('llm', as_index=False)[['query_in_token_len', 'query_out_token_len']].sum().itertuples():
		input_price = llm_description[row.llm]['input_price'] * (row.query_in_token_len / 1_000_000)
		output_price = llm_description[row.llm]['output_price'] * (row.query_out_token_len / 1_000_000)
		cost.append(input_price+output_price)
		print(
			f"{row.llm} (total tokens {row.query_in_token_len+row.query_out_token_len}): \n"
			f"input price: {input_price:.3f}\n"
			f"output price: {output_price:.3f}\n"
			f"total price: {input_price+output_price:.2f} $"
		)

		print()
	print(f"Predicted cost for dataset: {sum(cost)}")

df["query_in_token_len"] = df["query"].apply(count_tokens)
df["query_out_token_len"] = df["model_response"].apply(count_tokens)
calculate_price(df, llm_description)

GPT-4.1 (total tokens 135699):
input price: 0.042
output price: 0.916
total price: 0.96 $

Gemini 2.5 Pro (total tokens 94178):
input price: 0.020
output price: 0.782
total price: 0.80 $

LLlama-3.1 (8B) (total tokens 102853):
input price: 0.004
output price: 0.014
total price: 0.02 $

Meta Llama 3.1 70B Instruct Turbo (total tokens 90786):
input price: 0.021
output price: 0.058
total price: 0.08 $

Mixtral-8x7B Instruct v0.1 (total tokens 67914):
input price: 0.014
output price: 0.027
total price: 0.04 $

Qwen2.5 72B Instruct Turbo (total tokens 101029):
input price: 0.028
output price: 0.094
total price: 0.12 $

Qwen2.5 7B Instruct Turbo (total tokens 87911):
input price: 0.007
output price: 0.019
total price: 0.03 $

Predicted cost for dataset: 2.0469847199999998

In [121]:
for row in df.groupby('llm', as_index=False)[['query_in_token_len', 'query_out_token_len']].sum().itertuples():
	print(row.llm)
	break

GPT-4.1

In [105]:
df.groupby('llm')['query_out_token_len'].sum()

llm
GPT-4.1                              114455
Gemini 2.5 Pro                        78214
LLlama-3.1 (8B)                       78597
Meta Llama 3.1 70B Instruct Turbo     66456
Mixtral-8x7B Instruct v0.1            44625
Qwen2.5 72B Instruct Turbo            78077
Qwen2.5 7B Instruct Turbo             63286
Name: query_out_token_len, dtype: int64

In [85]:

for row in df.itertuples():
	print(row.task_id)
	break

hendrycks-MATH

In [59]:
df[(df["query_out_token_len"] >= 1500) & (df['effect'] == 0)].shape

(31, 15)

In [83]:
print(row[row['llm'] == "GPT-4.1"]['query'].values[0])

You are given a mathematics problem.

Solve the problem step by step and clearly explain your reasoning.

Your response must strictly follow the format below.

R:
Provide a clear, logical, and step-by-step mathematical reasoning.
Use equations and mathematical expressions when necessary.

A:
Write only the final answer, exactly matching the required mathematical form.
Do not add explanations, units, or extra text.

Question:
There exist nonzero integers $a$ and $b$ such that the quadratic
\[(ax - b)^2 + (bx - a)^2 = x\]has one integer root and one non-integer root.  Find the non-integer root.

In [78]:
row_info(row[row['llm'] == "LLlama-3.1 (8B)"])

LLM: 1097    LLlama-3.1 (8B)
Name: llm, dtype: object
length of ground_truth_reasoning: 1
length of model_response: 1
* ground_truth_reasoning:
 1097    The given equation expands to\n\[(a^2 + b^2) x...
Name: ground_truth_reasoning, dtype: object
* model_response:
 1097    R:\nTo solve this problem, we start by expandi...
Name: model_response, dtype: object

No structred output !!

In [ ]:
# filtred_df = df.drop(['effect', 'model_response'], axis=1)
# filtred_df[filtred_df.duplicated]

In [ ]:
import hashlib

def stable_hash(text: str, length: int = 16) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:length]

def build_uid(task_id, query, llm):
    q_hash = stable_hash(query)
    return f"{task_id}::{q_hash}::{llm}"#, q_hash



df['uid'] = df.apply(lambda row: build_uid(row['task_id'], row['query'], row['llm']), axis=1)

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::0fa23b219f0b1954::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.000038,3191009375396059475
1,hendrycks-MATH::0fa23b219f0b1954::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.000047,3191009375396059475
2,hendrycks-MATH::0fa23b219f0b1954::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.000006,3191009375396059475
3,hendrycks-MATH::0fa23b219f0b1954::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.000002,3191009375396059475
4,hendrycks-MATH::0fa23b219f0b1954::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.000004,3191009375396059475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,hendrycks-MATH::28b4ef3526fc54ab::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.55791601e-02 2.49049291e-02 9.05702356e...,\frac{2 \sqrt{149}}{3},"Let $A = (3,-5,7),$ the center of the first sp...",R:\nLet the two spheres be $S_1$ and $S_2$.\nT...,exact_match,Gemini 2.5 Pro,0,0.870644,-2646026841900602313
771,hendrycks-MATH::134fdc2705e5404c::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-6.85580121e-03 1.38404652e-01 -6.58040494e...,3\sqrt{3},Let's sketch our triangle first. We can see t...,R:\n1. **Identify the triangle's properties.*...,exact_match,Gemini 2.5 Pro,0,0.869448,-7522346823162821990
772,hendrycks-MATH::8b517a5ba22fa9fb::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-2.24011689e-02 8.40791464e-02 -8.10938329e...,10\sqrt{2},Drawing altitude $\overline{BD}$ splits $\tria...,R:\nLet the triangle be denoted as $\triangle ...,exact_match,Gemini 2.5 Pro,0,0.877339,1794305501350446657
773,hendrycks-MATH::5c9411267bd2a503::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.75931403e-02 5.94095923e-02 -6.87694326e...,3\sqrt{2},Utilizing the properties of geometric sequence...,R:\nThe problem provides two geometric sequenc...,exact_match,Gemini 2.5 Pro,0,0.868910,-7825709311146843122
774,hendrycks-MATH::98687363220fce8d::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nThis problem can be modeled using an arith...,exact_match,Gemini 2.5 Pro,0,0.870166,-4197463334678850961

In [24]:
# Split uid into components
uid_parts = df['uid'].str.split("::", expand=True)

df['query_uid'] = uid_parts[1]

In [25]:
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::0fa23b219f0b1954::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.000038,0fa23b219f0b1954
1,hendrycks-MATH::0fa23b219f0b1954::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.000047,0fa23b219f0b1954
2,hendrycks-MATH::0fa23b219f0b1954::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.000006,0fa23b219f0b1954
3,hendrycks-MATH::0fa23b219f0b1954::Mixtral-8x7B...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.000002,0fa23b219f0b1954
4,hendrycks-MATH::0fa23b219f0b1954::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.000004,0fa23b219f0b1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,hendrycks-MATH::28b4ef3526fc54ab::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.55791601e-02 2.49049291e-02 9.05702356e...,\frac{2 \sqrt{149}}{3},"Let $A = (3,-5,7),$ the center of the first sp...",R:\nLet the two spheres be $S_1$ and $S_2$.\nT...,exact_match,Gemini 2.5 Pro,0,0.870644,28b4ef3526fc54ab
771,hendrycks-MATH::134fdc2705e5404c::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-6.85580121e-03 1.38404652e-01 -6.58040494e...,3\sqrt{3},Let's sketch our triangle first. We can see t...,R:\n1. **Identify the triangle's properties.*...,exact_match,Gemini 2.5 Pro,0,0.869448,134fdc2705e5404c
772,hendrycks-MATH::8b517a5ba22fa9fb::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-2.24011689e-02 8.40791464e-02 -8.10938329e...,10\sqrt{2},Drawing altitude $\overline{BD}$ splits $\tria...,R:\nLet the triangle be denoted as $\triangle ...,exact_match,Gemini 2.5 Pro,0,0.877339,8b517a5ba22fa9fb
773,hendrycks-MATH::5c9411267bd2a503::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.75931403e-02 5.94095923e-02 -6.87694326e...,3\sqrt{2},Utilizing the properties of geometric sequence...,R:\nThe problem provides two geometric sequenc...,exact_match,Gemini 2.5 Pro,0,0.868910,5c9411267bd2a503
774,hendrycks-MATH::98687363220fce8d::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nThis problem can be modeled using an arith...,exact_match,Gemini 2.5 Pro,0,0.870166,98687363220fce8d

In [ ]:
df[df['llm'] == 'Gemini 2.5 Pro']

In [17]:
print(len(df[df['effect'] == 1])) # 412
df

412

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.000038,3191009375396059475
1,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.000047,3191009375396059475
2,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.000006,3191009375396059475
3,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.000002,3191009375396059475
4,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.000004,3191009375396059475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,hendrycks-MATH::-2646026841900602313::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.55791601e-02 2.49049291e-02 9.05702356e...,\frac{2 \sqrt{149}}{3},"Let $A = (3,-5,7),$ the center of the first sp...",R:\nLet the two spheres be $S_1$ and $S_2$.\nT...,exact_match,Gemini 2.5 Pro,0,0.870644,-2646026841900602313
771,hendrycks-MATH::-7522346823162821990::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-6.85580121e-03 1.38404652e-01 -6.58040494e...,3\sqrt{3},Let's sketch our triangle first. We can see t...,R:\n1. **Identify the triangle's properties.*...,exact_match,Gemini 2.5 Pro,0,0.869448,-7522346823162821990
772,hendrycks-MATH::1794305501350446657::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-2.24011689e-02 8.40791464e-02 -8.10938329e...,10\sqrt{2},Drawing altitude $\overline{BD}$ splits $\tria...,R:\nLet the triangle be denoted as $\triangle ...,exact_match,Gemini 2.5 Pro,0,0.877339,1794305501350446657
773,hendrycks-MATH::-7825709311146843122::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-7.75931403e-02 5.94095923e-02 -6.87694326e...,3\sqrt{2},Utilizing the properties of geometric sequence...,R:\nThe problem provides two geometric sequenc...,exact_match,Gemini 2.5 Pro,0,0.868910,-7825709311146843122
774,hendrycks-MATH::-4197463334678850961::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nThis problem can be modeled using an arith...,exact_match,Gemini 2.5 Pro,0,0.870166,-4197463334678850961

In [12]:
len(df['query_uid'].unique())
df['query_uid'].unique()[-20:]

array([-2691339547862347549,  3814853170806676602,  5289617142476636054,
       -3063127598285040437, -2436930183329781363, -5357476666624292878,
       -5631274021169221602,  2341690718030215046, -6212709914206167746,
        8946566077954292709, -1599213302491351506,  2210897758388067005,
         758101055065163836,  -735942193682170489,  4428510588133737247,
       -2646026841900602313, -7522346823162821990,  1794305501350446657,
       -7825709311146843122, -4197463334678850961], dtype=int64)

In [61]:
uid = -4197463334678850961
df[df['query_uid']==uid]

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
774,hendrycks-MATH::-4197463334678850961::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nThis problem can be modeled using an arith...,exact_match,Gemini 2.5 Pro,0,0.870166,-4197463334678850961

In [120]:
query = df[df['query_uid']=="16a5ad2fdf4f0280"]
query

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid,structure_response
1093,hendrycks-MATH::16a5ad2fdf4f0280::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.62054168e-02 1.21305235e-01 -1.96452253e...,\frac{1}{2},The given equation expands to\n\[(a^2 + b^2) x...,"R:\nFirst, expand the given quadratic:\n\[\n(a...",exact_match,GPT-4.1,0,4412.0,16a5ad2fdf4f0280,False
1094,hendrycks-MATH::16a5ad2fdf4f0280::Gemini 2.5 Pro,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.62054168e-02 1.21305235e-01 -1.96452253e...,\frac{1}{2},The given equation expands to\n\[(a^2 + b^2) x...,[LLM_ERROR] NoneType: None,exact_match,Gemini 2.5 Pro,0,5317.5,16a5ad2fdf4f0280,False
1095,hendrycks-MATH::16a5ad2fdf4f0280::Qwen2.5 72B ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.62054168e-02 1.21305235e-01 -1.96452253e...,\frac{1}{2},The given equation expands to\n\[(a^2 + b^2) x...,R:\nTo solve the given quadratic equation \((a...,exact_match,Qwen2.5 72B Instruct Turbo,0,804.0,16a5ad2fdf4f0280,False
1096,hendrycks-MATH::16a5ad2fdf4f0280::Meta Llama 3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.62054168e-02 1.21305235e-01 -1.96452253e...,\frac{1}{2},The given equation expands to\n\[(a^2 + b^2) x...,R:\nTo find the non-integer root of the given ...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,589.6,16a5ad2fdf4f0280,True
1097,hendrycks-MATH::16a5ad2fdf4f0280::LLlama-3.1 (8B),hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.62054168e-02 1.21305235e-01 -1.96452253e...,\frac{1}{2},The given equation expands to\n\[(a^2 + b^2) x...,"R:\nTo solve this problem, we start by expandi...",exact_match,LLlama-3.1 (8B),0,120.6,16a5ad2fdf4f0280,False
1098,hendrycks-MATH::16a5ad2fdf4f0280::Qwen2.5 7B I...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.62054168e-02 1.21305235e-01 -1.96452253e...,\frac{1}{2},The given equation expands to\n\[(a^2 + b^2) x...,"R:\nFirst, expand the given equation:\n\[\n(ax...",exact_match,Qwen2.5 7B Instruct Turbo,0,201.0,16a5ad2fdf4f0280,False

In [171]:
model_output = show_model_output(df, "16a5ad2fdf4f0280", "Qwen2.5 72B Instruct Turbo")
# print(df[(df['query_uid'] == "16a5ad2fdf4f0280") & (df["llm"] == "Qwen2.5 72B Instruct Turbo")].iloc[0].model_response)

R:
To solve the given quadratic equation \((ax - b)^2 + (bx - a)^2 = x\) and find the non-integer root, we will follow these steps:

1. **Expand and simplify the equation:**
   \[
   (ax - b)^2 + (bx - a)^2 = x
   \]
   Expanding both squares, we get:
   \[
   (ax - b)^2 = a^2x^2 - 2abx + b^2
   \]
   \[
   (bx - a)^2 = b^2x^2 - 2abx + a^2
   \]
   Adding these two expressions together:
   \[
   a^2x^2 - 2abx + b^2 + b^2x^2 - 2abx + a^2 = x
   \]
   Combine like terms:
   \[
   (a^2 + b^2)x^2 - 4abx + (a^2 + b^2) = x
   \]

2. **Rearrange the equation to standard quadratic form:**
   \[
   (a^2 + b^2)x^2 - 4abx + (a^2 + b^2) - x = 0
   \]
   Simplify:
   \[
   (a^2 + b^2)x^2 - (4ab + 1)x + (a^2 + b^2) = 0
   \]

3. **Identify the coefficients of the quadratic equation:**
   The quadratic equation is:
   \[
   (a^2 + b^2)x^2 - (4ab + 1)x + (a^2 + b^2) = 0
   \]
   Let \(A = a^2 + b^2\), \(B = -(4ab + 1)\), and \(C = a^2 + b^2\).

4. **Use the quadratic formula to find the roots:**
   The quadratic formula is:
   \[
   x = \frac{-B \pm \sqrt{B^2 - 4AC}}{2A}
   \]
   Substitute \(A\), \(B\), and \(C\):
   \[
   x = \frac{4ab + 1 \pm \sqrt{(4ab + 1)^2 - 4(a^2 + b^2)(a^2 + b^2)}}{2(a^2 + b^2)}
   \]

5. **Simplify the discriminant:**
   \[
   B^2 - 4AC = (4ab + 1)^2 - 4(a^2 + b^2)^2
   \]
   Expand and simplify:
   \[
   (4ab + 1)^2 = 16a^2b^2 + 8ab + 1
   \]
   \[
   4(a^2 + b^2)^2 = 4(a^4 + 2a^2b^2 + b^4) = 4a^4 + 8a^2b^2 + 4b^4
   \]
   \[
   B^2 - 4AC = 16a^2b^2 + 8ab + 1 - (4a^4 + 8a^2b^2 + 4b^4)
   \]
   \[
   B^2 - 4AC = 16a^2b^2 + 8ab + 1 - 4a^4 - 8a^2b^2 - 4b^4
   \]
   \[
   B^2 - 4AC = 8ab + 1 - 4a^4 - 4b^4
   \]

6. **Simplify the roots:**
   \[
   x = \frac{4ab + 1 \pm \sqrt{8ab + 1 - 4a^4 - 4b^4}}{2(a^2 + b^2)}
   \]

7. **Determine the nature of the roots:**
   Given that one root is an integer and the other is a non-integer, we need to find specific values of \(a\) and \(b\) that satisfy this condition. Let's test \(a = 1\) and \(b = 1\):
   \[
   A = 1^2 + 1^2 = 2
   \]
   \[
   B = -(4 \cdot 1 \cdot 1 + 1) = -5
   \]
   \[
   C = 1^2 + 1^2 = 2
   \]
   The quadratic equation becomes:
   \[
   2x^2 - 5x + 2 = 0
   \]
   Solve using the quadratic formula:
   \[
   x = \frac{5 \pm \sqrt{25 - 16}}{4}
   \]
   \[
   x = \frac{5 \pm 3}{4}
   \]
   \[
   x = 2 \quad \text{or} \quad x = \frac{1}{2}
   \]

8. **Identify the non-integer root:**
   The non-integer root is:
   \[
   x = \frac{1}{2}
   \]

A:
\[
\frac{1}{2}
\]

In [137]:
model_output

"R:\nTo solve the given quadratic equation \\((ax - b)^2 + (bx - a)^2 = x\\) and find the non-integer root, we will follow these steps:\n\n1. **Expand and simplify the equation:**\n   \\[\n   (ax - b)^2 + (bx - a)^2 = x\n   \\]\n   Expanding both squares, we get:\n   \\[\n   (ax - b)^2 = a^2x^2 - 2abx + b^2\n   \\]\n   \\[\n   (bx - a)^2 = b^2x^2 - 2abx + a^2\n   \\]\n   Adding these two expressions together:\n   \\[\n   a^2x^2 - 2abx + b^2 + b^2x^2 - 2abx + a^2 = x\n   \\]\n   Combine like terms:\n   \\[\n   (a^2 + b^2)x^2 - 4abx + (a^2 + b^2) = x\n   \\]\n\n2. **Rearrange the equation to standard quadratic form:**\n   \\[\n   (a^2 + b^2)x^2 - 4abx + (a^2 + b^2) - x = 0\n   \\]\n   Simplify:\n   \\[\n   (a^2 + b^2)x^2 - (4ab + 1)x + (a^2 + b^2) = 0\n   \\]\n\n3. **Identify the coefficients of the quadratic equation:**\n   The quadratic equation is:\n   \\[\n   (a^2 + b^2)x^2 - (4ab + 1)x + (a^2 + b^2) = 0\n   \\]\n   Let \\(A = a^2 + b^2\\), \\(B = -(4ab + 1)\\), and \\(C = a^2 + b^2\\).\n\n4. **Use the quadratic formula to find the roots:**\n   The quadratic formula is:\n   \\[\n   x = \\frac{-B \\pm \\sqrt{B^2 - 4AC}}{2A}\n   \\]\n   Substitute \\(A\\), \\(B\\), and \\(C\\):\n   \\[\n   x = \\frac{4ab + 1 \\pm \\sqrt{(4ab + 1)^2 - 4(a^2 + b^2)(a^2 + b^2)}}{2(a^2 + b^2)}\n   \\]\n\n5. **Simplify the discriminant:**\n   \\[\n   B^2 - 4AC = (4ab + 1)^2 - 4(a^2 + b^2)^2\n   \\]\n   Expand and simplify:\n   \\[\n   (4ab + 1)^2 = 16a^2b^2 + 8ab + 1\n   \\]\n   \\[\n   4(a^2 + b^2)^2 = 4(a^4 + 2a^2b^2 + b^4) = 4a^4 + 8a^2b^2 + 4b^4\n   \\]\n   \\[\n   B^2 - 4AC = 16a^2b^2 + 8ab + 1 - (4a^4 + 8a^2b^2 + 4b^4)\n   \\]\n   \\[\n   B^2 - 4AC = 16a^2b^2 + 8ab + 1 - 4a^4 - 8a^2b^2 - 4b^4\n   \\]\n   \\[\n   B^2 - 4AC = 8ab + 1 - 4a^4 - 4b^4\n   \\]\n\n6. **Simplify the roots:**\n   \\[\n   x = \\frac{4ab + 1 \\pm \\sqrt{8ab + 1 - 4a^4 - 4b^4}}{2(a^2 + b^2)}\n   \\]\n\n7. **Determine the nature of the roots:**\n   Given that one root is an integer and the other is a non-integer, we need to find specific values of \\(a\\) and \\(b\\) that satisfy this condition. Let's test \\(a = 1\\) and \\(b = 1\\):\n   \\[\n   A = 1^2 + 1^2 = 2\n   \\]\n   \\[\n   B = -(4 \\cdot 1 \\cdot 1 + 1) = -5\n   \\]\n   \\[\n   C = 1^2 + 1^2 = 2\n   \\]\n   The quadratic equation becomes:\n   \\[\n   2x^2 - 5x + 2 = 0\n   \\]\n   Solve using the quadratic formula:\n   \\[\n   x = \\frac{5 \\pm \\sqrt{25 - 16}}{4}\n   \\]\n   \\[\n   x = \\frac{5 \\pm 3}{4}\n   \\]\n   \\[\n   x = 2 \\quad \\text{or} \\quad x = \\frac{1}{2}\n   \\]\n\n8. **Identify the non-integer root:**\n   The non-integer root is:\n   \\[\n   x = \\frac{1}{2}\n   \\]\n\nA:\n\\[\n\\frac{1}{2}\n\\]"

In [224]:
# df[df['ground_truth_numeric'] in '%']
df[df['ground_truth_numeric'].str.contains('%', na=False)]

Empty DataFrame
Columns: [uid, task_id, task_description, task_description_embedding, query, query_embedding, ground_truth_numeric, ground_truth_reasoning, model_response, metric, llm, effect, cost, query_uid, structure_response, predicted_answer]
Index: []

In [4]:
import re

def normalize_text(s):
    s = re.sub(r'\\text\{([^}]*)\}', r'\1', s)
    s = s.lower().strip()
    return s
def normalize_unicode_math(expr: str) -> str:
    if not isinstance(expr, str):
        return expr

    # √2  -> sqrt(2)
    expr = re.sub(r'√\s*\(?([^\)]+)\)?', r'sqrt(\1)', expr)

    # Optional: handle other unicode symbols
    expr = expr.replace('×', '*')
    expr = expr.replace('÷', '/')
    expr = expr.replace('−', '-')

    return expr


from sympy import sympify, simplify
from sympy.parsing.latex import parse_latex

def fix_common_latex_typos(expr: str) -> str:
    if not isinstance(expr, str):
        return expr

    # Add missing backslash before common LaTeX commands
    expr = re.sub(r'(?<!\\)\bfrac\s*\{', r'\\frac{', expr)
    expr = re.sub(r'(?<!\\)\bsqrt\s*\{', r'\\sqrt{', expr)
    expr = re.sub(r'(?<!\\)\bcdot\b', r'\\cdot', expr)
    expr = re.sub(r'(?<!\\)\btimes\b', r'\\times', expr)

    return expr

def normalize_numeric_tokens(expr: str) -> str:
    if not isinstance(expr, str):
        return expr

    expr = expr.strip()

    # Remove escaped dollar sign and currency symbol
    expr = expr.replace(r'\$', '')
    expr = expr.replace('$', '')

    expr = re.sub(
        r'(\d+(\.\d+)?)\s*%',
        r'\1',
        expr
    )

    return expr


def strip_latex_math(expr: str) -> str:
    if not isinstance(expr, str):
        return expr

    expr = expr.strip()


    # Remove \( ... \)
    expr = re.sub(r'^\\\((.*)\\\)$', r'\1', expr)

    # Remove \[ ... \]
    expr = re.sub(r'^\\\[(.*)\\\]$', r'\1', expr)

    # Remove $ ... $
    expr = re.sub(r'^\$(.*)\$$', r'\1', expr)

    return expr.strip()

def parse_expr(expr):
    expr = strip_latex_math(expr)
    expr = fix_common_latex_typos(expr)
    expr = normalize_unicode_math(expr)
    expr = normalize_numeric_tokens(expr)

    # Try sympify first (handles 1/2, sqrt(2)/3, etc.)
    try:
        return sympify(expr)
    except Exception:
        pass

    # Fallback to LaTeX
    try:
        return parse_latex(expr)
    except Exception:
        raise ValueError(f"Could not parse expression: {expr}")

from sympy import simplify

def math_equal(uid, expr1, expr2):
    try:
        e1 = parse_expr(expr1)
        e2 = parse_expr(expr2)
        return simplify(e1 - e2) == 0
    except Exception as e:
        # optional: log instead of print in production
        print(f"\n[uid] {uid} >> math_equal error:", e)
        return False


import sympy as sp

def numeric_equal(expr1, expr2, tol=1e-6):
    try:
        e1 = float(sp.N(parse_expr(expr1)))
        e2 = float(sp.N(parse_expr(expr2)))
        return abs(e1 - e2) < tol
    except Exception:
        return False




def answer_match(uid, ans1, ans2):
    if ans1 is None or ans2 is None:
        return 0

    # 1. Normalized text match
    if normalize_text(ans1) == normalize_text(ans2):
        return 1

    # 2. Symbolic equivalence
    if math_equal(uid, ans1, ans2):
        return 1

    # 3. Numeric fallback
    if numeric_equal(ans1, ans2):
        return 1

    return 0


# answer_match('fake', 'June 20', '\\text{June 20}')
answer_match('fake', '36', '36%')

# answer_match('fake',"frac{1}{2}", '\\[\\frac{1}{2}\\]')
# True

# \frac{1}{2}
# A:
# \[
# \frac{1}{2}
# \]

# math_equal error: Could not parse expression: \[\frac{1}{12a^2br^2} = 1\]

1

In [6]:
# from data_processing.utils import extract_final_answer_from_response
import re
def extract_final_answer_from_response(response_text):
    if response_text is None:
        return None

    # text = response_text.replace("\n", " ").strip()
    text = response_text

    # answer_part = None
    # answer_patterns = [
    #     r"A:\s*(.*)$",
    #     r"Answer:\s*(.*)$"
    # ]

    # for pattern in answer_patterns:
    #     match = re.search(pattern, text, flags=re.IGNORECASE)
    #     if match:
    #         answer_part = match.group(1).strip()
    #         break


    # if answer_part is None:
    #     answer_part = text.split(".")[-1].strip()

    # answer_part = re.split(
    #     r"(therefore|thus|hence|so|which means)",
    #     answer_part,
    #     flags=re.IGNORECASE
    # )[0].strip()

    # boxed_match = re.search(r"\\boxed\s*\{(.+?)\}", answer_part)
    # if boxed_match:
    #     return boxed_match.group(1).strip()

    # if "=" in answer_part:
    #     rhs = answer_part.split("=")[-1].strip()
    #     if rhs:
    #         answer_part = rhs

    # if answer_part.startswith("$") and answer_part.endswith("$"):
    #     answer_part = answer_part[1:-1].strip()

    return text.split("A:")[-1].replace('\n', '').strip()
    # return answer_part if answer_part else None
    
# predicted = extract_final_answer_from_response(model_output)
# predicted.strip()

In [142]:
model_output

"R:\nTo solve the given quadratic equation \\((ax - b)^2 + (bx - a)^2 = x\\) and find the non-integer root, we will follow these steps:\n\n1. **Expand and simplify the equation:**\n   \\[\n   (ax - b)^2 + (bx - a)^2 = x\n   \\]\n   Expanding both squares, we get:\n   \\[\n   (ax - b)^2 = a^2x^2 - 2abx + b^2\n   \\]\n   \\[\n   (bx - a)^2 = b^2x^2 - 2abx + a^2\n   \\]\n   Adding these two expressions together:\n   \\[\n   a^2x^2 - 2abx + b^2 + b^2x^2 - 2abx + a^2 = x\n   \\]\n   Combine like terms:\n   \\[\n   (a^2 + b^2)x^2 - 4abx + (a^2 + b^2) = x\n   \\]\n\n2. **Rearrange the equation to standard quadratic form:**\n   \\[\n   (a^2 + b^2)x^2 - 4abx + (a^2 + b^2) - x = 0\n   \\]\n   Simplify:\n   \\[\n   (a^2 + b^2)x^2 - (4ab + 1)x + (a^2 + b^2) = 0\n   \\]\n\n3. **Identify the coefficients of the quadratic equation:**\n   The quadratic equation is:\n   \\[\n   (a^2 + b^2)x^2 - (4ab + 1)x + (a^2 + b^2) = 0\n   \\]\n   Let \\(A = a^2 + b^2\\), \\(B = -(4ab + 1)\\), and \\(C = a^2 + b^2\\).\n\n4. **Use the quadratic formula to find the roots:**\n   The quadratic formula is:\n   \\[\n   x = \\frac{-B \\pm \\sqrt{B^2 - 4AC}}{2A}\n   \\]\n   Substitute \\(A\\), \\(B\\), and \\(C\\):\n   \\[\n   x = \\frac{4ab + 1 \\pm \\sqrt{(4ab + 1)^2 - 4(a^2 + b^2)(a^2 + b^2)}}{2(a^2 + b^2)}\n   \\]\n\n5. **Simplify the discriminant:**\n   \\[\n   B^2 - 4AC = (4ab + 1)^2 - 4(a^2 + b^2)^2\n   \\]\n   Expand and simplify:\n   \\[\n   (4ab + 1)^2 = 16a^2b^2 + 8ab + 1\n   \\]\n   \\[\n   4(a^2 + b^2)^2 = 4(a^4 + 2a^2b^2 + b^4) = 4a^4 + 8a^2b^2 + 4b^4\n   \\]\n   \\[\n   B^2 - 4AC = 16a^2b^2 + 8ab + 1 - (4a^4 + 8a^2b^2 + 4b^4)\n   \\]\n   \\[\n   B^2 - 4AC = 16a^2b^2 + 8ab + 1 - 4a^4 - 8a^2b^2 - 4b^4\n   \\]\n   \\[\n   B^2 - 4AC = 8ab + 1 - 4a^4 - 4b^4\n   \\]\n\n6. **Simplify the roots:**\n   \\[\n   x = \\frac{4ab + 1 \\pm \\sqrt{8ab + 1 - 4a^4 - 4b^4}}{2(a^2 + b^2)}\n   \\]\n\n7. **Determine the nature of the roots:**\n   Given that one root is an integer and the other is a non-integer, we need to find specific values of \\(a\\) and \\(b\\) that satisfy this condition. Let's test \\(a = 1\\) and \\(b = 1\\):\n   \\[\n   A = 1^2 + 1^2 = 2\n   \\]\n   \\[\n   B = -(4 \\cdot 1 \\cdot 1 + 1) = -5\n   \\]\n   \\[\n   C = 1^2 + 1^2 = 2\n   \\]\n   The quadratic equation becomes:\n   \\[\n   2x^2 - 5x + 2 = 0\n   \\]\n   Solve using the quadratic formula:\n   \\[\n   x = \\frac{5 \\pm \\sqrt{25 - 16}}{4}\n   \\]\n   \\[\n   x = \\frac{5 \\pm 3}{4}\n   \\]\n   \\[\n   x = 2 \\quad \\text{or} \\quad x = \\frac{1}{2}\n   \\]\n\n8. **Identify the non-integer root:**\n   The non-integer root is:\n   \\[\n   x = \\frac{1}{2}\n   \\]\n\nA:\n\\[\n\\frac{1}{2}\n\\]"

In [ ]:
extract_final_answer_from_response

In [9]:
df['structure_response'] = df['model_response'].apply(
    check_structure
)

In [10]:
structure_info(df)

Wrong Structure output: 72
Structured output: 1046
Structured output with correct answer: 761
Structured output with wrong answer: 357

In [163]:
structure_info(df)

Wrong Structure output: 137
Structured output: 981
Structured output with correct answer: 762
Structured output with wrong answer: 356

In [ ]:
# df[df['uid']=="hendrycks-MATH::9d8ab1720ea077b0::Qwen2.5 72B Instruct Turbo"]
show_model_output(df, "9d8ab1720ea077b0", "Qwen2.5 72B Instruct Turbo")

In [7]:
df['predicted_answer'] = df['model_response'].apply(
    extract_final_answer_from_response
)

df['effect'] = df.apply(
    lambda row: answer_match(row['uid'], row['predicted_answer'], row['ground_truth_numeric']),
    axis=1
)

[uid] hendrycks-MATH::98a2d098bfccd214::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::d548ae52159856db::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Pow'

[uid] hendrycks-MATH::1a0b730f7cb52fdc::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: \mathbf{B}^{-1} = \begin{pmatrix} \frac{5}{13} & -\frac{3}{13} \\ -\frac{1}{13} & \frac{2}{13} \end{pmatrix}

[uid] hendrycks-MATH::1a0b730f7cb52fdc::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: \begin{pmatrix} 8 & 12 \\ -4 & 20 \end{pmatrix}

[uid] hendrycks-MATH::1a0b730f7cb52fdc::LLlama-3.1 (8B) >> math_equal error: Could not parse expression: \boxed{\begin{pmatrix} 8 & 12 \\ -4 & 20 \end{pmatrix}}

[uid] hendrycks-MATH::2754a77c25e25eeb::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::2b43ab8707caeb14::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::46466098c73a4073::LLlama-3.1 (8B) >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::19cebab815214cea::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::c949b143fe32b6b0::LLlama-3.1 (8B) >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Add'

[uid] hendrycks-MATH::310dbd88564f8fcb::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression:

[uid] hendrycks-MATH::28c7dd1bf27f05b1::GPT-4.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::28c7dd1bf27f05b1::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::00958680c17d2177::Qwen2.5 72B Instruct Turbo >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Equality'

[uid] hendrycks-MATH::00958680c17d2177::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Equality'

[uid] hendrycks-MATH::00958680c17d2177::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Equality'

[uid] hendrycks-MATH::00958680c17d2177::LLlama-3.1 (8B) >> math_equal error: unsupported operand type(s) for -: 'Symbol' and 'Equality'

[uid] hendrycks-MATH::00958680c17d2177::Qwen2.5 7B Instruct Turbo >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Equality'

[uid] hendrycks-MATH::0fc0955e74d45157::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: \(\

[uid] hendrycks-MATH::e9a55eca77a42102::Qwen2.5 72B Instruct Turbo >> math_equal error: Could not parse expression:

[uid] hendrycks-MATH::0be7d0a908a0c4cf::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::533aba64150215f5::LLlama-3.1 (8B) >> math_equal error: Could not parse expression: 5π/3

[uid] hendrycks-MATH::72705c7e3f6e2b21::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::43684e7291e525c3::GPT-4.1 >> math_equal error: Could not parse expression: (-\infty, 3) \cup (3, \infty)

[uid] hendrycks-MATH::43684e7291e525c3::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: The solution is (-∞, 3) ∪ (3, ∞).

[uid] hendrycks-MATH::43684e7291e525c3::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: (-\infty, 3) \cup (3, \infty)

[uid] hendrycks-MATH::43684e7291e525c3::LLlama-3.1 (8B) >> math_equal error: Could not parse expression: (-∞, 3) ∪ (3, ∞)

[uid] hendrycks-MATH::43684e7291e525c3::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: (- \infty, 3) \cup (3, \infty)

[uid] hendrycks-MATH::5cdf51a70678fc95::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: (-∞, 3] ∪ [4, ∞)

[uid] hendrycks-MATH::b25640851374cfb8::Qwen2.5 7B Instruct Turbo >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Add'

[uid] hendrycks-MATH::4c5f5c4e614bc3f3::GPT-4.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::4c5f5c4e614bc3f3::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::ca03ab3fd79039e5::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::62e3bf057b1ca940::GPT-4.1 >> math_equal error: Could not parse expression: \begin{pmatrix} -10 \\ 6 \end{pmatrix}

[uid] hendrycks-MATH::62e3bf057b1ca940::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: -\frac{17}{19} \mathbf{w} = -\frac{17}{19} \begin{pmatrix} 15 \\ -9 \end{pmatrix} = \begin{pmatrix} -\frac{255}{19} \\ \frac{153}{19} \end{pmatrix}.

[uid] hendrycks-MATH::62e3bf057b1ca940::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: \begin{pmatrix} -10 \\ 6 \end{pmatrix}

[uid] hendrycks-MATH::62e3bf057b1ca940::LLlama-3.1 (8B) >> math_equal error: Could not parse expression: \begin{pmatrix} -10 \\ 6 \end{pmatrix}

[uid] hendrycks-MATH::ece543a957a1b57f::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::397c222df462a046::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: D=(0,5,4)

[uid] hendrycks-MATH::397c222df462a046::LLlama-3.1 (8B) >> math_equal error: unsupported operand type(s) for -: 'tuple' and 'tuple'

[uid] hendrycks-MATH::5fa572021da35b39::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: (-∞, 1/8) ∪ (3, ∞)

[uid] hendrycks-MATH::5fa572021da35b39::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: (-∞, 3) ∪ (3, ∞)

[uid] hendrycks-MATH::5fa572021da35b39::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: (-\infty, 3) \cup (3, \infty)

[uid] hendrycks-MATH::403e6c66a36cd907::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::9bf3f3e421828a02::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: (\infty, -4) \cup (-4, 6) \cup (6, \infty)

[uid] hendrycks-MATH::9bf3f3e421828a02::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: (-\infty, -4) \cup (-4, 6) \cup (6, \infty)

[uid] hendrycks-MATH::9bf3f3e421828a02::LLlama-3.1 (8B) >> math_equal error: Could not parse expression: (-\infty, -4) \cup (-4, 6) \cup (6, \infty)

[uid] hendrycks-MATH::9bf3f3e421828a02::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: (-\infty, -4) \cup (-4, 6) \cup (6, \infty)

[uid] hendrycks-MATH::d24ca45157fc530a::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'tuple' and 'tuple'

[uid] hendrycks-MATH::d24ca45157fc530a::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: unsupported operand type(s) for -: 'One' and 'tuple'

[uid] hendrycks-MATH::987b5ed0aaea2470::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: BooleanAtom not allowed in this context.

[uid] hendrycks-MATH::2d6c2d9d782b1498::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: \left( 6, -\frac{3}{8} \right)

[uid] hendrycks-MATH::13feaea57b24d544::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::3ae4e9b660b03a64::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::98a2d098bfccd214::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::5c9411267bd2a503::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::5c9411267bd2a503::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: \[3\sqrt{2}\

[uid] hendrycks-MATH::5c9411267bd2a503::Gemini 2.5 Pro >> math_equal error: Could not parse expression:

[uid] hendrycks-MATH::f56d7bcf617da5d7::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Float'

[uid] hendrycks-MATH::28b4ef3526fc54ab::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: R:Let's denote the center of the first sphere as C_1=(3,-5,7) and its radius as r_1=5\sqrt{5}. Similarly, let's denote the center of the second sphere as C_2=(0,1,1) and its radius as r_2=2\sqrt{17}.The spheres intersect in a circle if the distance between their centers is less than the sum of their radii and greater than the difference of their radii:r_1 - r_2 < |C_1 - C_2| < r_1 + r_2.First, let's calculate the distance between the centers:|C_1 - C_2| = \sqrt{(3-0)^2+(-5-1)^2+(7-1)^2} = \sqrt{9+36+36} = \sqrt{81} = 9.

[uid] hendrycks-MATH::34f4cc624341a692::Mixtral-8x7B Instruct v0.1 >> math_equal error: BooleanAtom not allowed in this context.

[uid] hendrycks-MATH::ee93b8c09a9f3937::Mixtral-8x7B Instruct v0.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Integer'

[uid] hendrycks-MATH::80fab1d431425082::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: Could not parse expression: R:We are given the equation:\[3x + \frac{1}{2x} = 3.\]First, let's multiply both sides by 2x to eliminate the fraction:\[6x^2 + 1 = 6x.\]Now, let's rearrange the equation to form a quadratic equation:\[6x^2 - 6x + 1 = 0.\]This is a quadratic equation in the form ax^2 + bx + c = 0, where a = 6, b = -6, and c = 1.We can use the quadratic formula to solve for x:\[x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}.\]However, we don't need to find the exact value of x. Instead, we can use the fact that x satisfies the given equation to find the value of x^3.Let's cube both sides of the original equation:\[(3x + \frac{1}{2x})^3 = 3^3.\]Expanding the left-hand side using the binomial theorem, we get:\[27x^3 + \frac{1}{8x^3} + 3 \cdot 3x \cdot \frac{1}{2x} (3x + \frac{1}{2x}) = 27.\]Simplifying the equation, we get:\[27x^3 + \frac{1}{8x^3} + \frac{9}{2} (3x + \frac{1}{2x}) = 27.\]Substituting the original equation, we get:\[27x^3 + \frac{1}{8x^3} + \frac{9}{2} \cdot 3 = 27.\]Simplifying the equation, we get:\[27x^3 + \frac{1}{8x^3} = 0.\]Now, let's cube both sides again:\[(27x^3 + \frac{1}{8x^3})^3 = 0^3.\]Expanding the left-hand side using the binomial theorem, we get:\[19683x^9 + \frac{1}{512x^9} + 3 \cdot 27x^3 \cdot \frac{1}{8x^3} (27x^3 + \frac{1}{8x^3}) = 0.\]Simplifying the equation, we get:\[19683x^9 + \frac{1}{512x^9} = 0.\]Now, let's multiply both sides by 64x^3:\[64 \cdot 19683x^{12} + \frac{64}{512x^6} = 0.\]Simplifying the equation, we get:\[64 \cdot 19683x^{12} + \frac{1}{8x^6} = 0.\]Now, let's multiply both sides by 8x^6:\[64 \cdot 19683x^{18} + 1 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 27x^3 + 1/8x^3 = 0.Multiplying both sides by 64/27, we get:\[64x^3 + \frac{1}{27x^3} = 0.\]Cubing both sides, we get:\[64^3x^9 + \frac{1}{27^3x^9} + 3 \cdot 64x^3 \cdot \frac{1}{27x^3} (64x^3 + \frac{1}{27x^3}) = 0.\]Simplifying the equation, we get:\[64^3x^9 + \frac{1}{27^3x^9} = 0.\]Now, let's multiply both sides by 27^3x^3:\[64^3 \cdot 27^3x^{12} + 1 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]Now, let's divide both sides by 64^2:\[27x^9 + \frac{1}{64^2x^9} = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^3, we get:\[64^2x^6 + \frac{64}{27x^3} = 0.\]Multiplying both sides by 27x^3, we get:\[64^2 \cdot 27x^9 + 64 = 0.\]However, we are asked to find the value of 64x^6 + 1/729x^6.Let's go back to the equation 64x^3 + 1/27x^3 = 0.Multiplying both sides by 64x^

[uid] hendrycks-MATH::d548ae52159856db::Gemini 2.5 Pro >> math_equal error: unsupported operand type(s) for -: 'tuple' and 'Pow'

[uid] hendrycks-MATH::d548ae52159856db::Meta Llama 3.1 70B Instruct Turbo >> math_equal error: unsupported operand type(s) for -: 'tuple' and 'Pow'

[uid] hendrycks-MATH::d548ae52159856db::LLlama-3.1 (8B) >> math_equal error: BooleanAtom not allowed in this context.

[uid] hendrycks-MATH::1a0b730f7cb52fdc::GPT-4.1 >> math_equal error: Could not parse expression: \begin{pmatrix} 8 & 12 \\ -4 & 20 \end{pmatrix}

[uid] hendrycks-MATH::1a0b730f7cb52fdc::Gemini 2.5 Pro >> math_equal error: Could not parse expression: \begin{pmatrix} 8 & 12 \\ -4 & 20 \end{pmatrix}

[uid] hendrycks-MATH::1a0b730f7cb52fdc::Qwen2.5 72B Instruct Turbo >> math_equal error: Could not parse expression: \begin{pmatrix} \frac{2}{13} & \frac{3}{13} \\ -\frac{1}{13} & \frac{5}{13} \end{pmatrix}

[uid] hendrycks-MATH::1a0b730f7cb52fdc::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: \begin{pmatrix} 8 & 12 \\ -4 & 20 \end{pmatrix}

[uid] hendrycks-MATH::f2621eb909d1f849::Mixtral-8x7B Instruct v0.1 >> math_equal error: Could not parse expression: R:The equation currently is:\[4x + 6 + 7x -

[uid] hendrycks-MATH::2b43ab8707caeb14::GPT-4.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::2b43ab8707caeb14::Gemini 2.5 Pro >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::9b17fac3d640f265::Mixtral-8x7B Instruct v0.1 >> math_equal error: BooleanAtom not allowed in this context.

[uid] hendrycks-MATH::46466098c73a4073::Gemini 2.5 Pro >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Mul'

[uid] hendrycks-MATH::c949b143fe32b6b0::Qwen2.5 7B Instruct Turbo >> math_equal error: Could not parse expression: R:Let's start by expanding and simplifying the given equation:\[x^4 + (2-x)^4 = 34\]Expanding \((2-x)^4\):\[(2-x)^4 = (2-x)^2(2-x)^2 = (4 - 4x + x^2)(4 - 4x + x^2) = x^4 - 8x^3 + 24x^2 - 32x + 16\]So the equation becomes:\[x^4 + x^4 - 8x^3 + 24x^2 - 32x + 16 = 34\]\[2x^4 - 8x^3 + 24x^2 - 32x - 18 = 0\]\[x^4 - 4x^3 + 12x^2 - 16x - 9 = 0\]To solve this polynomial equation, we can try to find rational roots using the Rational Root Theorem, which suggests that any rational solution, \(p/q\), is a factor of the constant term (-9) divided by a factor of the leading coefficient (1). The possible rational roots are \(\pm 1, \pm 3, \pm 9\).Testing \(x = 3\):\[3^4 - 4(3^3) + 12(3^2) - 16(3) - 9 = 81 - 108 + 108 - 48 - 9 = 0\]So, \(x = 3\) is a root.We can now factor \(x - 3\) out of the polynomial using synthetic division or polynomial division. Dividing \(x^4 - 4x^3 + 12x^2 - 16x - 9\) by \(x - 3\), we get:\[x^4 - 4x^3 + 12x^2 - 16x - 9 = (x - 3)(x^3 - x^2 + 5x + 3)\]Next, we need to solve \(x^3 - x^2 + 5x + 3 = 0\). Testing possible rational roots again, we find that \(x = -1\) is a root:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 - 5 + 3 = -4 + 3 = -2 \neq 0\]Testing \(x = -1\) again:\[-1^3 - (-1)^2 + 5(-1) + 3 = -1 - 1 -

[uid] hendrycks-MATH::00958680c17d2177::GPT-4.1 >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Equality'

[uid] hendrycks-MATH::00958680c17d2177::Gemini 2.5 Pro >> math_equal error: unsupported operand type(s) for -: 'Equality' and 'Equality'


In [8]:
df[df['effect']==1].shape

(689, 15)

In [180]:
df[df['effect']==1].shape

(645, 15)

In [28]:
df = df[df['model_response'].str.contains('[LLM_ERROR]', regex=False, na=False) == False]

In [30]:
df = df.drop(['predicted_answer', 'structure_response'], axis=1)

In [33]:
df.to_csv(ROUTER_PATH, index=False)

In [56]:
from data_processing.llm_engine import LLMEngine

import json, os
# File I/O functions
def loadjson(filename: str) -> dict:
    """
    Load data from a JSON file.

    Args:
        filename: Path to the JSON file

    Returns:
        Dictionary containing the loaded JSON data
    """
    with open(filename, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data

data_dir = "data/hendrycks-MATH/"
llm_path = os.path.join(data_dir, "LLM_Descriptions.json")
llm_description = loadjson(llm_path)

engine = LLMEngine(
            llm_description=llm_description
        )

for i, row in enumerate(df.itertuples()):		
	df.loc[i, 'cost'] = engine.compute_cost(
		llm_name=row.llm,
		input_text=row.query,
		output_size=512
	)

In [90]:
df_no_text = df.iloc[idx]
df_with_text = df.drop(index=idx)
print("df_with_text cols:", len(df_with_text.columns))

df_no_text = df_no_text.drop(['Unnamed: 0.1', 'Unnamed: 0', "OMS"], axis=1)
print("df_no_text cols:", len(df_no_text.columns))
df_no_text.head()

df_with_text cols: 17
df_no_text cols: 14

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.804881,3.191009e+18
1,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.981020,3.191009e+18
2,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.124622,3.191009e+18
3,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.051737,3.191009e+18
4,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.085750,3.191009e+18

In [130]:
# Split uid into components
uid_parts = df_no_text['uid'].str.split("::", expand=True)
df_no_text['query_uid'] = uid_parts[1]
num_unique_queries = df_no_text['query_uid'].nunique()
print("Number of unique queries:", num_unique_queries)

Number of unique queries: 147

In [131]:
correccted_df_with_text = pd.DataFrame({
	"uid": df_with_text['Unnamed: 0.1'],
	"task_id": df_with_text['Unnamed: 0'],
	"task_description": df_with_text['uid'],
	"task_description_embedding": df_with_text['task_id'],
	"query": df_with_text['task_description'],
	"query_embedding": df_with_text['task_description_embedding'],
	"ground_truth_numeric": df_with_text['query'],
	"ground_truth_reasoning": df_with_text['query_embedding'],
	"model_response": df_with_text['ground_truth_numeric'], 
	"metric": df_with_text['ground_truth_reasoning'],
	"llm": df_with_text['model_response'],
	"effect": df_with_text['metric'],
	"cost": df_with_text['llm'],
	'query_uid': df_with_text['effect']
})

In [132]:
correccted_df_with_text.head()

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
710,hendrycks-MATH::-2691339547862347549::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nA vertical asymptote occurs where the deno...,exact_match,GPT-4.1,1,16640.0,-2691339547862347549
711,hendrycks-MATH::-2691339547862347549::DeepSeek...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,"<think>\nFirst, I need to find how many vertic...",exact_match,DeepSeek R1-0528,0,14720.0,-2691339547862347549
712,hendrycks-MATH::-2691339547862347549::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nA vertical asymptote of a rational functio...,exact_match,Gemini 2.5 Pro,1,20640.0,-2691339547862347549
713,hendrycks-MATH::-2691339547862347549::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,2611.2,-2691339547862347549
714,hendrycks-MATH::-2691339547862347549::Mixtral-...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,1305.6,-2691339547862347549

In [133]:
print(len(df_no_text.columns))
df_no_text.columns

14

Index(['uid', 'task_id', 'task_description', 'task_description_embedding',
       'query', 'query_embedding', 'ground_truth_numeric',
       'ground_truth_reasoning', 'model_response', 'metric', 'llm', 'effect',
       'cost', 'query_uid'],
      dtype='object')

In [103]:
print(len(correccted_df_with_text.columns))
correccted_df_with_text.columns

14

Index(['uid', 'task_id', 'task_description', 'task_description_embedding',
       'query', 'query_embedding', 'ground_truth_numeric',
       'ground_truth_reasoning', 'model_response', 'metric', 'llm', 'effect',
       'cost', 'query_uid'],
      dtype='object')

In [161]:
correccted_df_with_text.iloc[:8]

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
710,hendrycks-MATH::-2691339547862347549::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nA vertical asymptote occurs where the deno...,exact_match,GPT-4.1,1,16640.0,-2691339547862347549
711,hendrycks-MATH::-2691339547862347549::DeepSeek...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,"<think>\nFirst, I need to find how many vertic...",exact_match,DeepSeek R1-0528,0,14720.0,-2691339547862347549
712,hendrycks-MATH::-2691339547862347549::Gemini 2...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nA vertical asymptote of a rational functio...,exact_match,Gemini 2.5 Pro,1,20640.0,-2691339547862347549
713,hendrycks-MATH::-2691339547862347549::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,2611.2,-2691339547862347549
714,hendrycks-MATH::-2691339547862347549::Mixtral-...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,1305.6,-2691339547862347549
715,hendrycks-MATH::-2691339547862347549::Meta Lla...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,1914.88,-2691339547862347549
716,hendrycks-MATH::-2691339547862347549::LLlama-3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,LLlama-3.1 (8B),1,391.68,-2691339547862347549
717,hendrycks-MATH::-2691339547862347549::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 7B Instruct Turbo,1,652.8,-2691339547862347549

In [162]:
df_no_text

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.804881,3191009375396059475
1,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.981020,3191009375396059475
2,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.124622,3191009375396059475
3,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.051737,3191009375396059475
4,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.085750,3191009375396059475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,hendrycks-MATH::4420519635866588408::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we ...",exact_match,Mixtral-8x7B Instruct v0.1,0,0.055267,4420519635866588408
706,hendrycks-MATH::4420519635866588408::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we n...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0,0.090928,4420519635866588408
707,hendrycks-MATH::4420519635866588408::LLlama-3....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we n...",exact_match,LLlama-3.1 (8B),1,0.001777,4420519635866588408
708,hendrycks-MATH::4420519635866588408::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of \(A\), \(B\), and...",exact_match,Qwen2.5 7B Instruct Turbo,1,0.017060,4420519635866588408
709,hendrycks-MATH::-4377496244889683276::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...",A:\n\(\frac{13}{9}\),exact_match,Qwen2.5 7B Instruct Turbo,0,0.022014,-4377496244889683276

In [163]:
final_data = pd.concat([df_no_text, correccted_df_with_text])  
print(final_data.shape)
final_data

(790, 14)

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,query_uid
0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.804881,3191009375396059475
1,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.98102,3191009375396059475
2,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.124622,3191009375396059475
3,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.051737,3191009375396059475
4,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.08575,3191009375396059475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,hendrycks-MATH::8946566077954292709::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nTo determine the date in June when Connie ...,exact_match,Qwen2.5 72B Instruct Turbo,0,2646.0,8946566077954292709
786,hendrycks-MATH::8946566077954292709::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nLet's reason through this problem. Connie...,exact_match,Mixtral-8x7B Instruct v0.1,0,1323.0,8946566077954292709
787,hendrycks-MATH::8946566077954292709::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nTo find the date when Connie will first do...,exact_match,Meta Llama 3.1 70B Instruct Turbo,0,1940.4,8946566077954292709
788,hendrycks-MATH::8946566077954292709::LLlama-3....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...",R:\nTo find the date when Connie first does mo...,exact_match,LLlama-3.1 (8B),0,396.9,8946566077954292709
789,hendrycks-MATH::8946566077954292709::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 4.55764704e-04 8.35925043e-02 1.44818248e...,\text{June 20},"On June $n$th, Connie will do $25 + 4(n-1)$ si...","R:\nTo solve this problem, we need to determin...",exact_match,Qwen2.5 7B Instruct Turbo,0,661.5,8946566077954292709

In [164]:
final_data.to_csv("data/hendrycks-MATH/router_data.csv", index=False)

In [4]:
models_per_query = df.groupby('query_uid')['llm'].nunique()
models_per_query.value_counts()

llm
7    104
6     34
5     12
4      6
1      4
3      4
Name: count, dtype: int64

In [11]:

# df['cost'] = df.groupby('task_id')['cost'].transform(
# 	lambda x: (x - x.min()) / (x.max() - x.min() + 1e-8)
# )
# df

In [12]:
# df.to_csv('data/hendrycks-MATH/router_data.csv', index=False)

In [ ]:
# df = df.loc[:, ~df.columns.str.startswith('Unnamed')]
# df.to_csv("data/hendrycks-MATH/router_data.csv", index=False)

In [4]:
df.head()

,Unnamed: 0.1,Unnamed: 0,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,OMS,query_uid
0,0,0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.804881,0.946471,3.191009e+18
1,1,1,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.981020,0.922840,3.191009e+18
2,2,2,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.124622,0.927195,3.191009e+18
3,3,3,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.051737,0.820935,3.191009e+18
4,4,4,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.085750,0.943133,3.191009e+18

In [6]:
df['cost'] = df.groupby('task_id')['cost'].transform(
	lambda x: (x - x.min()) / (x.max() - x.min() + 1e-8)
)

df.head()

,Unnamed: 0.1,Unnamed: 0,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,OMS,query_uid
0,0,0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,0.804881,0.946471,3191009375396059475
1,1,1,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,0.981020,0.922840,3191009375396059475
2,2,2,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,0.124622,0.927195,3191009375396059475
3,3,3,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,0.051737,0.820935,3191009375396059475
4,4,4,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,0.085750,0.943133,3191009375396059475

In [5]:
df['model_response'][0]

'R:\nVertical asymptotes occur where the denominator of a rational function is zero, provided the numerator is not also zero at those points.\n\nGiven the function: \n\\[ y = \\frac{2}{x^2 + x - 6} \\]\n\nFirst, find the values of \\( x \\) where the denominator equals zero:\n\\[\nx^2 + x - 6 = 0\n\\]\n\nFactor the quadratic:\n\\[\n(x + 3)(x - 2) = 0\n\\]\n\nSet each factor equal to zero:\n\\[\nx + 3 = 0 \\implies x = -3 \\\\\nx - 2 = 0 \\implies x = 2\n\\]\n\nCheck the numerator at these points:\nThe numerator is 2, which is nonzero at both \\( x = -3 \\) and \\( x = 2 \\).\nThus, both are vertical asymptotes.\n\nA:\n2'

In [130]:
df['uid'][1192:1194][:35]

1192    hendrycks-MATH::-4377496244889683276::LLlama-3...
1193    hendrycks-MATH::-4377496244889683276::Qwen2.5 ...
Name: uid, dtype: object

In [131]:
df.shape[0] // 8

149

In [ ]:
df

In [ ]:
# idx = 0
# llmlen = 9
# df[idx:idx+llmlen]
len(df['uid'] .unique())

1194

In [2]:
import re

# Common patterns for Answer section
answer_patterns = [
	r"A:\s*(.*)$",        # A: ....
]
	# r"Answer:\s*(.*)$"    # Answer: ....



# Compile the answer patterns into regex patterns (case-insensitive, multiline)
answer_regexes = [re.compile(pattern, re.MULTILINE) for pattern in answer_patterns]

def contains_answer_pattern(text):
    if not isinstance(text, str):
        return False
    return any(regex.search(text) for regex in answer_regexes)

# Filter all rows where 'model_response' contains any of the answer patterns
model_response_with_answer = df[df['model_response'].apply(contains_answer_pattern)]

model_response_with_answer  # This DataFrame contains all such rows

,Unnamed: 0,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,OMS
0,0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,4352.00,0.946471
2,2,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,5280.00,0.922840
3,3,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,768.00,0.927195
4,4,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,384.00,0.820935
5,5,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,563.20,0.943133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,1178,hendrycks-MATH::4420519635866588408::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we ...",exact_match,Mixtral-8x7B Instruct v0.1,0,402.60,0.000000
1179,1179,hendrycks-MATH::4420519635866588408::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we n...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0,590.48,0.000000
1180,1180,hendrycks-MATH::4420519635866588408::LLlama-3....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we n...",exact_match,LLlama-3.1 (8B),1,120.78,0.918953
1181,1181,hendrycks-MATH::4420519635866588408::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of \(A\), \(B\), and...",exact_match,Qwen2.5 7B Instruct Turbo,1,201.30,0.793780
1193,1193,hendrycks-MATH::-4377496244889683276::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...",A:\n\(\frac{13}{9}\),exact_match,Qwen2.5 7B Instruct Turbo,0,227.40,0.000000

In [16]:
model_response_with_answer.to_csv("data/hendrycks-MATH/router_data.csv", index=False)

In [7]:
# Split uid into components
uid_parts = model_response_with_answer['uid'].str.split("::", expand=True)

model_response_with_answer['query_uid'] = uid_parts[1]

num_unique_queries = model_response_with_answer['query_uid'].nunique()
print("Number of unique queries:", num_unique_queries)

Number of unique queries: 147

C:\Users\CMG\AppData\Local\Temp\ipykernel_8664\4168152228.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_response_with_answer['query_uid'] = uid_parts[1]

In [ ]:
models_per_query = model_response_with_answer.groupby('query_uid')['llm'].nunique()

models_per_query.value_counts()

count    147.000000
mean       4.829932
std        1.949268
min        1.000000
25%        3.000000
50%        5.000000
75%        6.000000
max        8.000000
Name: llm, dtype: float64

In [15]:
models_per_query.value_counts()

llm
5    37
6    29
7    26
2    13
3    13
1    12
4    11
8     6
Name: count, dtype: int64

In [3]:
model_response_with_answer['model_response'][1180]

"R:\nTo compare the values of A, B, and C, we need to express them in a common form. \n\nFirst, let's rewrite B and C in terms of square roots:\nB = (4)^(1/4) = ((2^2)^(1/2))^(1/4) = (2^(2/2))^(1/4) = (2^1)^(1/4) = 2^(1/4)\nC = (8)^(1/8) = ((2^3)^(1/3))^(1/8) = (2^(3/3))^(1/8) = (2^1)^(1/8) = 2^(1/8)\n\nNow, let's rewrite A in terms of 2:\nA = √2 = (2)^(1/2)\n\nNow we can compare the values of A, B, and C by comparing their exponents:\nA = 2^(1/2)\nB = 2^(1/4)\nC = 2^(1/8)\n\nSince 1/2 > 1/4 > 1/8, we can conclude that C has the least value.\n\nA:\nC"

In [133]:
df[df['effect'] == 1]

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost
0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,4352.00
2,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,5280.00
3,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,768.00
4,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,384.00
5,hendrycks-MATH::3191009375396059475::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of the gra...,exact_match,Meta Llama 3.1 70B Instruct Turbo,1,563.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151,hendrycks-MATH::4895189913777562895::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.19826789e-02 1.19557425e-01 -6.87449500e...,108,Since the sum of the angles in a triangle is $...,R:\nThe sum of the interior angles in any tria...,exact_match,Qwen2.5 7B Instruct Turbo,1,226.20
1173,hendrycks-MATH::7760910048174239467::Meta Llam...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 2.03119847e-03 8.22888762e-02 -1.36672081e...,18,"Since the area of rectangle $PQRS$ is $24,$ le...","R:\nTo find the area of quadrilateral $PTRS$, ...",exact_match,Meta Llama 3.1 70B Instruct Turbo,1,741.84
1177,hendrycks-MATH::4420519635866588408::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,R:\nTo determine which of the given values \(A...,exact_match,Qwen2.5 72B Instruct Turbo,1,805.20
1180,hendrycks-MATH::4420519635866588408::LLlama-3....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of A, B, and C, we n...",exact_match,LLlama-3.1 (8B),1,120.78
1181,hendrycks-MATH::4420519635866588408::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 7.14484081e-02 1.41986445e-01 -2.64430679e...,C,If we simplify all of the quantities and make ...,"R:\nTo compare the values of \(A\), \(B\), and...",exact_match,Qwen2.5 7B Instruct Turbo,1,201.30

In [6]:

# df = pd.read_csv('data/GSM8K/final_data.csv')
df = pd.read_csv('data/hendrycks-MATH/final_data.csv')
df.head()

,data,difficulty,llm,Cost,CR,OMS,Normalized_CR,Normalized_OMS
0,hendrycks-MATH,Hard,DeepSeek R1-0528,4070.600000,0.200000,0.176992,0.000000,0.000000
1,hendrycks-MATH,Hard,GPT-4.1,4394.680851,0.648936,0.545824,0.687560,0.647869
2,hendrycks-MATH,Hard,Gemini 2.5 Pro,5294.080882,0.852941,0.746293,1.000000,1.000000
3,hendrycks-MATH,Hard,LLlama-3.1 (8B),120.891667,0.527778,0.455190,0.502002,0.488666
4,hendrycks-MATH,Hard,Meta Llama 3.1 70B Instruct Turbo,591.592727,0.652893,0.562198,0.693619,0.676631

In [12]:
df['query'][0]

'You are given a mathematics problem.\n\nSolve the problem step by step and clearly explain your reasoning.\n\nYour response must strictly follow the format below.\n\nR:\nProvide a clear, logical, and step-by-step mathematical reasoning.\nUse equations and mathematical expressions when necessary.\n\nA:\nWrite only the final answer, exactly matching the required mathematical form.\nDo not add explanations, units, or extra text.\n\nQuestion:\nHow many vertical asymptotes does the graph of $y=\\frac{2}{x^2+x-6}$ have?'

In [18]:
from dotenv import load_dotenv
from typing import List, Optional, Tuple
import os, requests, json
load_dotenv() 

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"


def _openrouter_completion(
    model: str,
    prompt: str,
    max_tokens: int,
    temperature: float,
    top_p: Optional[float],
) -> str:
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        # Optional but recommended by OpenRouter
        "HTTP-Referer": "http://localhost",
        "X-Title": "LLM Selection Project",
    }

    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }

    if top_p is not None:
        payload["top_p"] = top_p

    response = requests.post(
        OPENROUTER_URL,
        headers=headers,
        data=json.dumps(payload),
        timeout=60,
    )

    response.raise_for_status()
    data = response.json()

    return data["choices"][0]["message"]["content"]

answer = _openrouter_completion(
	'google/gemini-2.5-pro',
	df['query'][0],
	2048,
	0.0,
	None
)

In [114]:
import re

def extract_final_answer_from_response(response_text):
    """
    Extract final answer (string-safe) from the Answer (A:) section.
    Supports:
    - LaTeX answers (\\frac{}, \\pi, etc.)
    - Symbolic answers (p - q, x^2)
    - Single-character answers (e.g., C)
    - Numeric answers (with or without formatting)
    """

    if response_text is None:
        return None

    # Normalize text
    text = response_text.replace("\n", " ").strip()

    # --------------------------------------------------
    # 1️⃣ Extract Answer section (A:)
    # --------------------------------------------------
    answer_part = None
    answer_patterns = [
        r"A:\s*(.*)$",
        r"Answer:\s*(.*)$"
    ]

    for pattern in answer_patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            answer_part = match.group(1).strip()
            break

    # Fallback: last sentence
    if answer_part is None:
        answer_part = text.split(".")[-1].strip()

    # --------------------------------------------------
    # 2️⃣ Remove trailing reasoning phrases
    # --------------------------------------------------
    answer_part = re.split(
        r"(therefore|thus|hence|so|which means)",
        answer_part,
        flags=re.IGNORECASE
    )[0].strip()

    # --------------------------------------------------
    # 3️⃣ Handle boxed answers
    # --------------------------------------------------
    boxed_match = re.search(r"\\boxed\s*\{(.+?)\}", answer_part)
    if boxed_match:
        return boxed_match.group(1).strip()

    # --------------------------------------------------
    # 4️⃣ Handle equality (take RHS safely)
    # --------------------------------------------------
    if "=" in answer_part:
        rhs = answer_part.split("=")[-1].strip()
        if rhs:
            answer_part = rhs

    # --------------------------------------------------
    # 5️⃣ Clean outer $...$
    # --------------------------------------------------
    answer_part = answer_part.strip()
    if answer_part.startswith("$") and answer_part.endswith("$"):
        answer_part = answer_part[1:-1].strip()

    return answer_part if answer_part else None



# extract_final_answer_from_response(model_response_with_answer['model_response'][1180])

df['predicted_answer'] = df['model_response'].apply(
    extract_final_answer_from_response
)


def is_numeric_ground_truth(gt):
    return bool(re.fullmatch(r"-?\d+(\.\d+)?", str(gt).strip()))

def normalize_numeric_answer(text):
    """
    Normalize numeric answers safely.
    Supports:
    - 2
    - 2.5
    - $108^\\circ$
    - 108°
    - 108 degrees
    """

    if text is None:
        return None

    text = str(text)

    # Remove degree-like annotations
    text = re.sub(r"\^\\circ", "", text)
    text = re.sub(r"[°]", "", text)
    text = re.sub(r"(degrees?|deg)", "", text, flags=re.I)

    # Remove latex noise
    text = text.replace("\\,", "").replace("$", "").strip()

    # ✅ Correct regex (NO capturing group)
    match = re.search(r"-?\d+(?:\.\d+)?", text)

    return match.group(0) if match else None


def compute_em(predicted, ground_truth):
    if predicted is None or ground_truth is None:
        return 0

    gt = str(ground_truth).strip()
    pred = str(predicted).strip()

    # Case 1: numeric ground truth
    if is_numeric_ground_truth(gt):
        pred_num = normalize_numeric_answer(pred)
        return 1 if str(pred_num) == str(gt) else 0

    # Case 2: non-numeric → string match
    return 1 if pred == gt else 0


df['predicted_answer'] = df['model_response'].apply(
    extract_final_answer_from_response
)

df['EM'] = df.apply(
    lambda row: compute_em(
        row['predicted_answer'],
        row['ground_truth_numeric']
    ),
    axis=1
)


# ground_truth_numeric -> ground truth column

In [115]:
normalize_numeric_answer('2')

'2'

In [116]:
df

,uid,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,predicted_answer,EM
0,hendrycks-MATH::3191009375396059475::GPT-4.1,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nVertical asymptotes occur where the denomi...,exact_match,GPT-4.1,1,4352.00,2,1
1,hendrycks-MATH::3191009375396059475::DeepSeek ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,"<think>\nFirst, I need to find how many vertic...",exact_match,DeepSeek R1-0528,0,3968.00,And,0
2,hendrycks-MATH::3191009375396059475::Gemini 2....,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nThe given function is a rational function ...,exact_match,Gemini 2.5 Pro,1,5280.00,2,1
3,hendrycks-MATH::3191009375396059475::Qwen2.5 7...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo determine the number of vertical asympt...,exact_match,Qwen2.5 72B Instruct Turbo,1,768.00,2,1
4,hendrycks-MATH::3191009375396059475::Mixtral-8...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[ 1.87039617e-02 6.16644509e-02 -4.59855311e...,2,The denominator of the rational function facto...,R:\nTo find the vertical asymptotes of a rati...,exact_match,Mixtral-8x7B Instruct v0.1,1,384.00,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,hendrycks-MATH::-4377496244889683276::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...","R:\nTo solve the given problem, we need to sum...",exact_match,Qwen2.5 72B Instruct Turbo,0,909.60,The general term of the series can be written ...,0
1190,hendrycks-MATH::-4377496244889683276::Mixtral-...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...",R:\nLet's find the sum of each column:\n\nFir...,exact_match,Mixtral-8x7B Instruct v0.1,0,454.80,None,0
1191,hendrycks-MATH::-4377496244889683276::Meta Lla...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...","R:\nTo solve this problem, we can represent ea...",exact_match,Meta Llama 3.1 70B Instruct Turbo,0,667.04,10/9 + (1/9)(1 + 1/10 + 1/,0
1192,hendrycks-MATH::-4377496244889683276::LLlama-3...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...","R:\nTo solve this problem, we can observe a pa...",exact_match,LLlama-3.1 (8B),0,136.44,We can rewrite the sum as follows: $1 + \left...,0
1193,hendrycks-MATH::-4377496244889683276::Qwen2.5 ...,hendrycks-MATH,Competition-level mathematics problems.,[[ 3.85295739e-03 6.32412061e-02 2.88434885e...,You are given a mathematics problem.\n\nSolve ...,[[-3.85024957e-02 5.48795536e-02 -1.67897958e...,\frac{100}{81},"The first addend, $1.11111111\ldots$, is by it...",A:\n\(\frac{13}{9}\),exact_match,Qwen2.5 7B Instruct Turbo,0,227.40,\(\frac{13}{9}\),0

In [101]:
def compute_em(pred, gt):
    if pred is None or gt is None:
        return 0
    return int(str(pred).strip() == str(gt).strip())

df['EM'] = df.apply(
    lambda row: compute_em(
        row['predicted_answer'],
        row['ground_truth_numeric']
    ),
    axis=1
)

In [120]:
# df[df['EM'] == 1] 

# df[df['effect'] == 1]
df['effect'] = df['EM']

In [126]:
df = df.drop(['predicted_answer', 'EM'], axis=1)

In [128]:
df.to_csv("data/hendrycks-MATH/router_data.csv", index=False)

In [105]:
df['model_response'][1149]

"R:\nTo find the largest angle in $\\triangle PQR$, we need to use the fact that the sum of the interior angles of a triangle is always $180^\\circ$. \n\nLet's denote the angles as follows:\n- $\\angle PQR = 6x^\\circ$\n- $\\angle QRP = x^\\circ$\n- $\\angle QPR = 3x^\\circ$\n\nWe can write the equation based on the sum of the interior angles of a triangle:\n$\\angle PQR + \\angle QRP + \\angle QPR = 180^\\circ$\n$6x^\\circ + x^\\circ + 3x^\\circ = 180^\\circ$\n$10x^\\circ = 180^\\circ$\n\nNow, we can solve for $x$:\n$x = \\frac{180^\\circ}{10}$\n$x = 18^\\circ$\n\nNow that we have the value of $x$, we can find the largest angle in $\\triangle PQR$:\n$\\angle PQR = 6x^\\circ$\n$\\angle PQR = 6 \\cdot 18^\\circ$\n$\\angle PQR = 108^\\circ$\n\nA:\n$108^\\circ$"

In [ ]:
from data_processing.utils import savepkl, loadjson, get_embedding

In [ ]:
# from typing import List, Optional, Tuple

# from sentence_transformers import SentenceTransformer
# model = SentenceTransformer('all-MiniLM-L6-v2')
# def get_embedding(instructions: List[str]) -> np.ndarray:
#     """
#     Get embeddings for a list of texts and optionally reduce dimensions.

#     Args:
#         instructions: List of texts to embed
#         dim: Target dimension for embeddings

#     Returns:
#         Numpy array of embeddings
#     """
#     emb_list = model.encode(instructions)
#     return emb_list

In [ ]:
import re

def extract_reasoning(response_text):
    if response_text is None:
        return ""
    if "A:" in response_text:
        return response_text.split("A:")[0]
    return response_text


def reasoning_structure_score(reasoning_text):
    if not reasoning_text:
        return 0.0

    score = 0

    # step indicators
    if re.search(r"(first|then|next|finally|step)", reasoning_text, re.I):
        score += 0.4

    # math operators
    if re.search(r"[\+\-\*/=]", reasoning_text):
        score += 0.3

    # length (not too short)
    if len(reasoning_text.split()) > 20:
        score += 0.3

    return min(score, 1.0)

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def semantic_similarity(emb1, emb2):
    emb1 = np.array(emb1).reshape(1, -1)
    emb2 = np.array(emb2).reshape(1, -1)
    return cosine_similarity(emb1, emb2)[0][0]


def compute_rqs(model_reasoning,
                gt_reasoning,
                model_emb,
                gt_emb,
                alpha=0.5):

    structure = reasoning_structure_score(model_reasoning)
    semantic = semantic_similarity(model_emb, gt_emb)

    return alpha * structure + (1 - alpha) * semantic

def compute_oms(effect, rqs, beta=0.3):
    if effect == 0:
        return 0.0
    return beta + (1 - beta) * rqs


def add_oms_to_dataframe(df, alpha=0.5, beta=0.3):

    oms_list = []

    for _, row in df.iterrows():
        model_reasoning = extract_reasoning(row['model_response'])
        gt_reasoning = row['ground_truth_reasoning']

        model_emb = get_embedding([model_reasoning])[0]
        gt_emb = get_embedding([gt_reasoning])[0]

        rqs = compute_rqs(
            model_reasoning,
            gt_reasoning,
            model_emb,
            gt_emb,
            alpha=alpha
        )

        oms = compute_oms(row['effect'], rqs, beta)
        oms_list.append(oms)

    df['OMS'] = oms_list
    return df


oms_df = add_oms_to_dataframe(df)

In [7]:
oms_df

,task_id,task_description,task_description_embedding,query,query_embedding,ground_truth_numeric,ground_truth_reasoning,model_response,metric,llm,effect,cost,OMS
0,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763111e-02 8.01854953e-02 3.90714481e...,"Given a simple mathematical question, please d...",[[ 2.64247060e-02 1.31825447e-01 -1.34285982e...,4,Jennifer bought twice as many as Emily (who bo...,"R: First, let's find out how many candies Emi...",GSM8K,Mistral-7b,1,1.0,0.948171
1,GSM8K,The GSM8K dataset is tailored for mathematical...,[[-8.20763111e-02 8.01854953e-02 3.90714481e...,"Given a simple mathematical question, please d...",[[ 2.64247060e-02 1.31825447e-01 -1.34285982e...,4,Jennifer bought twice as many as Emily (who bo...,R: Let's denote the number of candies Bob boug...,GSM8K,LLlama-3.1 (8B),1,0.0,0.822153

In [ ]:
summary = (
    df.groupby(['task_id', 'llm'])
      .agg(
          CR=('effect', 'mean'),
          OMS=('OMS', 'mean'),
          Cost=('cost', 'mean')
      )
      .reset_index()
)

summary['Normalized_CR'] = summary.groupby('task_id')['CR'].transform(
    lambda x: (x - x.min()) / (x.max() - x.min())
)

summary['Normalized_OMS'] = summary.groupby('task_id')['OMS'].transform(
    lambda x: (x - x.min()) / (x.max() - x.min())
)

In [11]:
summary

  task_id              llm   CR       OMS  Cost  Normalized_CR  Normalized_OMS
0   GSM8K  LLlama-3.1 (8B)  1.0  0.822153   0.0            NaN             0.0
1   GSM8K       Mistral-7b  1.0  0.948171   1.0            NaN             1.0

In [3]:
df['model_response'][0]

" R: First, let's find out how many candies Emily bought: A = 6 candies.\nNext, we find out how many candies Jennifer bought, which is twice as many as Emily: B = 2 * A = 2 * 6 = <<12>>12 candies.\nFinally, we find out how many candies Bob bought, which is three times less than Jennifer: C = B / 3.\nA: <<12/3=4>>4 candies"

In [4]:
df['model_response'][1]

"R: Let's denote the number of candies Bob bought as 'x'. Since Jennifer bought three times as many candies as Bob, Jennifer bought 3x candies. Emily bought 6 candies, and Jennifer bought twice as many candies as Emily, so Jennifer bought 2 * 6 = 12 candies. Since Jennifer bought 3x candies and 12 candies, we can set up the equation 3x = 12 to find the value of 'x'.\nA: <4>"

In [1]:
import pandas as pd
from scipy.special import softmax

df = pd.read_csv("data/MIZAN_PersianNLG/router_data.csv")

idx = 0
block = df[idx*6 : idx*6+6]

# Compute values
max_effect = block[['llm', 'effect']].loc[block['effect'].idxmax()]
max_cost   = block[['llm', 'cost']].loc[block['cost'].idxmax()]
min_cost   = block[['llm', 'cost']].loc[block['cost'].idxmin()]

# Build a results table
results = pd.DataFrame([
    {'metric': 'max_effect', 'llm': max_effect['llm'], 'value': max_effect['effect']},
    {'metric': 'min_cost',   'llm': min_cost['llm'],   'value': min_cost['cost']},
])
results

       metric              llm     value
0  max_effect  LLlama-3.1 (8B)  0.625000
1    min_cost   Gemma-3N (e4b)  0.000757

In [2]:
idx = 0
block = df[idx*6 : idx*6+6].reset_index(drop=True)

# ---------------------------
# Normalize effect & cost
# ---------------------------
effect = block["effect"]
cost   = block["cost"]

effect_n = (effect - effect.min()) / (effect.max() - effect.min() + 1e-9)
cost_n   = (cost   - cost.min())   / (cost.max()   - cost.min()   + 1e-9)

# ---------------------------
# Compute scores for 3 scenarios
# ---------------------------

# 1️⃣ Performance First (effect only)
score_perf = effect_n

# 2️⃣ Balance (your formula)
score_bal  = 0.6 * effect_n - 0.4 * cost_n

# 3️⃣ Cost First (cost only, reversed → minimizing cost)
score_cost = -cost_n

# Temperature softmax (your formula)
T = 0.15
soft_perf = softmax(score_perf / T)
soft_bal  = softmax(score_bal  / T)
soft_cost = softmax(score_cost / T)

block["score_perf"] = soft_perf
block["score_bal"]  = soft_bal
block["score_cost"] = soft_cost

# ---------------------------
# Extract winners (ground truth)
# ---------------------------
winner_perf = block.loc[block["score_perf"].idxmax(), ["llm", "score_perf"]]
winner_bal  = block.loc[block["score_bal"].idxmax(),  ["llm", "score_bal"]]
winner_cost = block.loc[block["score_cost"].idxmax(), ["llm", "score_cost"]]

# ---------------------------
# Build final results table
# ---------------------------
results = pd.DataFrame([
    {"scenario": "Performance First", "llm": winner_perf["llm"], "score": winner_perf["score_perf"]},
    {"scenario": "Balance",           "llm": winner_bal["llm"],  "score": winner_bal["score_bal"]},
    {"scenario": "Cost First",        "llm": winner_cost["llm"], "score": winner_cost["score_cost"]},
])

results

            scenario              llm     score
0  Performance First  LLlama-3.1 (8B)  0.920270
1            Balance  LLlama-3.1 (8B)  0.707729
2         Cost First   Gemma-3N (e4b)  0.562095

In [2]:
import pandas as pd

df = pd.read_csv("data/MIZAN_PersianNLG/feedback/router_data.csv")
df.shape[0]//6
# idx = 3
# df[idx*6 : idx*6+6]

1054

In [41]:


# # ============================================
# # Normalize effect & cost
# # ============================================
# effect = block["effect"].astype(float)
# cost   = block["cost"].astype(float)

# effect_n = (effect - effect.min()) / (effect.max() - effect.min() + 1e-12)
# cost_n   = (cost   - cost.min())   / (cost.max()   - cost.min()   + 1e-12)




# # ============================================
# # Feedback weighting
# # ============================================
# alpha = 0.70  # same α you use when training the router


# # ============================================
# # Compute baseline scenario scores
# # ============================================

# # 1️⃣ Performance First
# score_perf = effect_n.copy()

# # 2️⃣ Balance
# score_bal = (0.6 * effect_n) - (0.4 * cost_n)

# # 3️⃣ Cost First
# score_cost = -cost_n

# # ============================================
# # Inject feedback (same rule as router code)
# # ============================================
# score_perf = (1 - alpha) * score_perf + alpha * feedback_n
# score_bal  = (1 - alpha) * score_bal  + alpha * feedback_n
# score_cost = (1 - alpha) * score_cost + alpha * feedback_n


# # ============================================
# # Apply softmax temperature scaling
# # ============================================
# T = 0.15
# soft_perf = softmax(score_perf / T)
# soft_bal  = softmax(score_bal  / T)
# soft_cost = softmax(score_cost / T)

# block["score_perf"] = soft_perf
# block["score_bal"]  = soft_bal
# block["score_cost"] = soft_cost


# # ============================================
# # Extract winners
# # ============================================
# winner_perf = block.loc[block["score_perf"].idxmax(), ["llm", "score_perf"]]
# winner_bal  = block.loc[block["score_bal"].idxmax(),  ["llm", "score_bal"]]
# winner_cost = block.loc[block["score_cost"].idxmax(), ["llm", "score_cost"]]


# # ============================================
# # Build final results table
# # ============================================
# results = pd.DataFrame([
#     {"scenario": "Performance First", "llm": winner_perf["llm"], "score": winner_perf["score_perf"]},
#     {"scenario": "Balance",           "llm": winner_bal["llm"],  "score": winner_bal["score_bal"]},
#     {"scenario": "Cost First",        "llm": winner_cost["llm"], "score": winner_cost["score_cost"]},
# ])

from typing import Any


def compute_winners_table(block, alpha=0.4, T=0.15):
    """
    Compute winning LLMs under different scenarios with feedback and softmax scaling.

    Parameters:
        block: pd.DataFrame (must contain ['effect', 'cost', 'feedback_n', 'llm'])
        alpha: float (weight of feedback in score combination)
        T: float (softmax temperature)

    Returns:
        results: pd.DataFrame (scenario, llm, score)
    """
    # Normalizing effect and cost
    effect_n = (block["effect"] - block["effect"].min()) / (block["effect"].max() - block["effect"].min() + 1e-12)
    cost_n = (block["cost"] - block["cost"].min()) / (block["cost"].max() - block["cost"].min() + 1e-12)
    
    # ============================================
    # Load and normalize feedback (same as router)
    # ============================================
    
    if "avg_feedback" in block.columns:
        feedback_list = block["avg_feedback"].fillna(0).astype(float).values

        # Normalize feedback if > 1.0 (assumes 1–5 rating)
        if feedback_list.max() > 1.0:
            FEEDBACK_MIN_SCORE = 1.0
            FEEDBACK_NORMALIZED_RANGE = 4.0  # (5 - 1)
            feedback_list = (feedback_list - FEEDBACK_MIN_SCORE) / FEEDBACK_NORMALIZED_RANGE

        # Feedback min-max normalization
        feedback_n = (feedback_list - feedback_list.min()) / (feedback_list.max() - feedback_list.min() + 1e-12)

    else:
        feedback_n = np.zeros(len(block))



    # Baseline scores
    score_perf = effect_n.copy()
    score_bal = (0.6 * effect_n) - (0.4 * cost_n)
    score_cost = -cost_n

    # Inject feedback
    score_perf = (1 - alpha) * score_perf + alpha * feedback_n
    score_bal  = (1 - alpha) * score_bal  + alpha * feedback_n
    score_cost = (1 - alpha) * score_cost + alpha * feedback_n

    # Softmax
    def softmax(x):
        x = np.array(x)
        x = x - np.max(x)
        e_x = np.exp(x / T)
        return e_x / (e_x.sum() + 1e-12)

    soft_perf = softmax(score_perf)
    soft_bal = softmax(score_bal)
    soft_cost = softmax(score_cost)

    block = block.copy()
    block["score_perf"] = soft_perf
    block["score_bal"] = soft_bal
    block["score_cost"] = soft_cost

    # Winners
    # winner_perf = block.loc[block["score_perf"].idxmax(), ["llm", "score_perf"]]
    # winner_bal  = block.loc[block["score_bal"].idxmax(),  ["llm", "score_bal"]]
    # winner_cost = block.loc[block["score_cost"].idxmax(), ["llm", "score_bal"]]



    # results = pd.DataFrame([
    #     {"scenario": "Performance First", "llm": winner_perf["llm"], "score": winner_perf["score_perf"]},
    #     {"scenario": "Balance",           "llm": winner_bal["llm"],  "score": winner_bal["score_bal"]},
    #     {"scenario": "Cost First",        "llm": winner_cost["llm"], "score": winner_cost["score_cost"]},
    # ])
    results = pd.DataFrame( {
        "llm": block["llm"], 
        "score cost": block["score_cost"],
        "score balance": block["score_bal"],
        "score performance first": block["score_perf"],

    } )
    return results

import pandas as pd
import numpy as np
from scipy.special import softmax

df = pd.read_csv("data/MIZAN_PersianNLG/router_data.csv")
# df = pd.read_csv("data/MIZAN_PersianNLG/feedback/router_data.csv")


idx = 1
block = df[idx*6 : idx*6+6].reset_index(drop=True)

alpha = 0.4  # same α you use when training the router
T = 0.15

# Example usage (after block is defined):
results = compute_winners_table(block, alpha=alpha, T=T)

results

               llm  score cost  score balance  score performance first
0       Mistral-7b    0.123151       0.204431                 0.212288
1  LLlama-3.1 (8B)    0.141577       0.304558                 0.375918
2     Mixtral-8x7B    0.007574       0.008565                 0.006885
3      gpt-oss-20B    0.252820       0.384058                 0.375918
4    Qwen-2.5 (7b)    0.061329       0.029834                 0.013668
5   Gemma-3N (e4b)    0.413548       0.068555                 0.015323